#include "Demos/MaterialRefreshSurfaceDemo.h"

#include "Runtime/AssetRefreshDiagnostics.h"
#include "Runtime/AssetRefreshExecutor.h"
#include "Runtime/MaterialImportPipeline.h"
#include "Runtime/MeshImportPipeline.h"
#include "Runtime/RenderCamera.h"
#include "Runtime/SceneMeshAdapter.h"
#include "Runtime/SoftwareRenderer.h"
#include "Runtime/SoftwareSurfacePresenter.h"

#include <string>
#include <vector>

namespace NeoEngine {
bool RunMaterialRefreshSurfaceDemo(const MaterialRefreshSurfaceDemoConfig& config, MaterialRefreshSurfaceDemoReceipt& receipt, MaterialRefreshSurfaceDemoError& error) {
    receipt={};error=MaterialRefreshSurfaceDemoError::None;if(config.width<32U||config.height<32U||config.width>1024U||config.height>1024U||config.frames<2U||config.frames>600U||config.ppmPath.empty()||config.ppmPath.size()>256U){error=MaterialRefreshSurfaceDemoError::InvalidConfiguration;return false;}
    AssetRegistry registry;TextureStagingStore textures;MeshStagingStore meshes;MaterialStagingStore materials;AssetRefreshDiagnostics diagnostics;AssetRefreshExecutor refreshExecutor;MeshImportPipeline meshImport;MaterialImportPipeline materialImport;MeshImportReceipt meshReceipt{};MaterialImportReceipt materialReceipt{};const std::string obj="v -0.9 -0.8 3\nv 0.9 -0.8 3\nv 0.9 0.9 3\nv -0.9 0.9 3\nvn 0 0 -1\nf 1//1 2//1 3//1 4//1\n";const std::vector<uint8_t> initial{'n','e','w','m','t','l',' ','p','l','a','n','e','\n','K','d',' ','0','.','2',' ','0','.','8',' ','0','.','2','\n'};const std::vector<uint8_t> replacement{'n','e','w','m','t','l',' ','p','l','a','n','e','\n','K','d',' ','0','.','8',' ','0','.','1',' ','0','.','2','\n'};
    if(!meshImport.ImportObj(registry,meshes,"refresh-surface.mesh",{},std::vector<uint8_t>(obj.begin(),obj.end()),{},meshReceipt)){error=MaterialRefreshSurfaceDemoError::MeshImportFailed;return false;}if(!materialImport.ImportMtl(registry,materials,"refresh-surface.material",{},initial,"plane",materialReceipt)){error=MaterialRefreshSurfaceDemoError::MaterialImportFailed;return false;}const CpuMeshResource* mesh=meshes.Find("refresh-surface.mesh");const CpuMaterialResource* before=materials.Find("refresh-surface.material","plane");if(mesh==nullptr||before==nullptr){error=MaterialRefreshSurfaceDemoError::SceneBindFailed;return false;}
    SceneWorld world;SceneEntity entity{};if(!world.Create(entity)){error=MaterialRefreshSurfaceDemoError::WorldCreateFailed;return false;}if(!world.SetTransform(entity,{})||!world.UpdateTransforms()){error=MaterialRefreshSurfaceDemoError::TransformFailed;return false;}SceneMeshAdapter scene; if(!scene.AddStaged(entity,*mesh,*before)){error=MaterialRefreshSurfaceDemoError::SceneBindFailed;return false;}
    SoftwareRenderer renderer;RenderCamera camera;SoftwareSurfacePresenter surface;if(!renderer.Initialize(config.width,config.height)){error=MaterialRefreshSurfaceDemoError::RendererInitializeFailed;return false;}if(!camera.Initialize({RenderCameraMode::Perspective,{},5.0F,60.0F,static_cast<float>(config.width)/static_cast<float>(config.height),0.1F,20.0F})){error=MaterialRefreshSurfaceDemoError::CameraInitializeFailed;return false;}if(!surface.Initialize({config.width,config.height,config.hiddenSurface})){error=MaterialRefreshSurfaceDemoError::SurfaceInitializeFailed;return false;}constexpr uint32_t kClear=0xFF101420U;const DirectionalLight light{{0.0F,0.0F,-1.0F},1.0F};
    if(!renderer.Clear(kClear)){error=MaterialRefreshSurfaceDemoError::ClearFailed;return false;}if(!scene.Draw(world,camera,renderer,light)){error=MaterialRefreshSurfaceDemoError::SceneDrawFailed;return false;}if(!surface.PumpEvents()){error=MaterialRefreshSurfaceDemoError::SurfacePumpFailed;return false;}if(surface.CloseRequested()){error=MaterialRefreshSurfaceDemoError::SurfaceCloseRequested;return false;}if(!surface.Present(renderer)){error=MaterialRefreshSurfaceDemoError::SurfacePresentFailed;return false;}const uint64_t beforeFrameHash=renderer.FrameHash();const uint64_t beforeMaterialHash=materialReceipt.contentHash;const uint32_t beforeRgba=materialReceipt.rgba;
    if(!registry.ReplaceBytes("refresh-surface.material",replacement)||!diagnostics.BuildPlan(registry,"refresh-surface.material",textures,meshes,materials,scene)||diagnostics.Entries().size()!=2U||!refreshExecutor.ExecuteAtomic(diagnostics.Entries(),registry,textures,meshes,materials,scene)){error=MaterialRefreshSurfaceDemoError::MaterialRefreshFailed;return false;}const CpuMaterialResource* after=materials.Find("refresh-surface.material","plane");if(after==nullptr||!materials.IsCurrent(registry,"refresh-surface.material","plane")||refreshExecutor.Receipts().size()!=2U){error=MaterialRefreshSurfaceDemoError::SceneRefreshFailed;return false;}materialReceipt={after->assetId,after->materialName,after->sourceHash,after->material.rgba};
    for(uint32_t frame=1U;frame<config.frames;++frame){if(!renderer.Clear(kClear)){error=MaterialRefreshSurfaceDemoError::ClearFailed;return false;}if(!scene.Draw(world,camera,renderer,light)){error=MaterialRefreshSurfaceDemoError::SceneDrawFailed;return false;}if(!surface.PumpEvents()){error=MaterialRefreshSurfaceDemoError::SurfacePumpFailed;return false;}if(surface.CloseRequested()){error=MaterialRefreshSurfaceDemoError::SurfaceCloseRequested;return false;}if(!surface.Present(renderer)){error=MaterialRefreshSurfaceDemoError::SurfacePresentFailed;return false;}}
    if(!renderer.WritePpm(config.ppmPath)){error=MaterialRefreshSurfaceDemoError::ArtifactWriteFailed;return false;}uint32_t visible=0U;for(uint32_t pixel:renderer.Pixels())if(pixel!=kClear)++visible;receipt={config.frames,static_cast<uint32_t>(surface.PresentedFrameCount()),visible,beforeFrameHash,renderer.FrameHash(),beforeMaterialHash,materialReceipt.contentHash,beforeRgba,materialReceipt.rgba};return true;
}
} // namespace NeoEngine
