#include "Demos/NpcRouteAnimationSurfaceDemo.h"

#include "Runtime/AnimationLocomotionBridge.h"
#include "Runtime/AnimationSpriteTintBinding.h"
#include "Runtime/GridRouteFollower.h"
#include "Runtime/PhysicsAnimationLocomotionBridge.h"
#include "Runtime/RenderCamera.h"
#include "Runtime/SceneSpriteAdapter.h"
#include "Runtime/SoftwareRenderer.h"
#include "Runtime/SoftwareSurfacePresenter.h"
#include "Runtime/SpriteBatch.h"
#include "Runtime/TextureImportPipeline.h"

#include <cmath>
#include <vector>

namespace NeoEngine {
bool RunNpcRouteAnimationSurfaceDemo(const NpcRouteAnimationSurfaceDemoConfig& config, NpcRouteAnimationSurfaceDemoReceipt& receipt, NpcRouteAnimationSurfaceDemoError& error) {
    receipt = {}; error = NpcRouteAnimationSurfaceDemoError::None;
    if (config.width < 32U || config.height < 32U || config.width > 1024U || config.height > 1024U || config.frames < 5U || config.frames > 600U || config.ppmPath.empty() || config.ppmPath.size() > 256U) { error = NpcRouteAnimationSurfaceDemoError::InvalidConfiguration; return false; }
    AssetRegistry registry; TextureStagingStore textures; TextureImportPipeline textureImport; TextureImportReceipt textureReceipt{}; const std::vector<uint8_t> ppm{'P','6','\n','1',' ','1','\n','2','5','5','\n',255U,185U,70U};
    if (!textureImport.Import(registry, textures, "npc-route-demo.sprite", {}, ppm, TextureImportFormat::PpmP6, textureReceipt)) { error = NpcRouteAnimationSurfaceDemoError::TextureImportFailed; return false; }
    SceneWorld world; SceneEntity entity{}; if (!world.Create(entity) || !world.SetTransform(entity, {0.0F,0.0F,3.0F,0.0F,0.0F,0.0F,1.0F,1.0F,1.0F}) || !world.UpdateTransforms()) { error = NpcRouteAnimationSurfaceDemoError::WorldCreateFailed; return false; }
    GridNavigation navigation; if (!navigation.Initialize(4U)) { error = NpcRouteAnimationSurfaceDemoError::NavigationFailed; return false; } GridRouteFollower follower; const GridCell route[]{{0U,3U},{1U,3U},{1U,2U}}; if (!follower.SetRoute(route)) { error = NpcRouteAnimationSurfaceDemoError::RouteFailed; return false; } KinematicMotionController controller; if (!controller.Initialize({2.0F,0.25F,false})) { error = NpcRouteAnimationSurfaceDemoError::ControllerFailed; return false; }
    ArchetypeManager entities; GameplayPhysicsBodyBuilder bodies; EntityID body{}; if (!bodies.CreateCircleBody(entities,{GameplayPhysicsBodyType::Dynamic,0.0F,0.0F,0.0F,0.0F,0.5F,1.0F},body)) { error = NpcRouteAnimationSurfaceDemoError::PhysicsBodyFailed; return false; }
    AnimationTimeline timeline; if (!timeline.AddTrack("idle",{{0.0F,0.0F},{1.0F,0.0F}}) || !timeline.AddTrack("move",{{0.0F,1.0F},{1.0F,1.0F}})) { error = NpcRouteAnimationSurfaceDemoError::TimelineFailed; return false; } AnimationStateMachine animation; if (!animation.AddState({"idle","idle",AnimationPlayback::Loop}) || !animation.AddState({"move","move",AnimationPlayback::Loop}) || !animation.AddTransition({"start_move","idle","move",0.0F}) || !animation.AddTransition({"stop_move","move","idle",0.0F}) || !animation.Start("idle")) { error = NpcRouteAnimationSurfaceDemoError::StateMachineFailed; return false; } AnimationLocomotionBridge locomotion; if (!locomotion.Initialize({"start_move","stop_move",0.01F})) { error = NpcRouteAnimationSurfaceDemoError::LocomotionInitializeFailed; return false; } PhysicsAnimationLocomotionBridge physicsBridge; AnimationSpriteTintBinding tintBinding; if (!tintBinding.Initialize({0xFFFFFFFFU,0xFF70B0FFU})) { error = NpcRouteAnimationSurfaceDemoError::TintBindingFailed; return false; }
    const CpuTextureResource* texture=textures.Find("npc-route-demo.sprite"); SceneSpriteAdapter sprites; if (texture==nullptr || !sprites.AddStaged(entity,*texture,0.75F,0.75F,0,0,0xFFFFFFFFU)) { error = NpcRouteAnimationSurfaceDemoError::SpriteBindFailed; return false; } SoftwareRenderer renderer; RenderCamera camera; SoftwareSurfacePresenter surface; if (!renderer.Initialize(config.width,config.height)) { error = NpcRouteAnimationSurfaceDemoError::RendererInitializeFailed; return false; } if (!camera.Initialize({RenderCameraMode::Orthographic,{},5.0F,60.0F,static_cast<float>(config.width)/static_cast<float>(config.height),0.1F,10.0F})) { error = NpcRouteAnimationSurfaceDemoError::CameraInitializeFailed; return false; } if (!surface.Initialize({config.width,config.height,config.hiddenSurface})) { error = NpcRouteAnimationSurfaceDemoError::SurfaceInitializeFailed; return false; }
    constexpr uint32_t kClear=0xFF101420U; MovementAuthorityGate authority; float sampled=0.0F; uint32_t routeTintFrames=0U; uint64_t tintHash=1469598103934665603ULL;
    for(uint32_t frame=0; frame<config.frames; ++frame) { float velocityX=0.0F,velocityZ=0.0F; if(!follower.ReachedGoal()) { RouteIntent intent{}; if(!follower.PeekIntent(world,entity,navigation,intent)) { error=NpcRouteAnimationSurfaceDemoError::RouteFailed; return false; } const Transform3* current=world.GetLocalTransform(entity); if(current==nullptr) { error=NpcRouteAnimationSurfaceDemoError::TransformFailed; return false; } const float dx=intent.targetX-current->x,dz=intent.targetZ-current->z,distance=std::sqrt(dx*dx+dz*dz); if(!std::isfinite(distance)) { error=NpcRouteAnimationSurfaceDemoError::RouteFailed; return false; } if(distance>0.0001F) { velocityX=dx/distance*controller.UnitsPerSecond(); velocityZ=dz/distance*controller.UnitsPerSecond(); } if(!bodies.SetDynamicPlanarVelocity(entities,body,velocityX,velocityZ)) { error=NpcRouteAnimationSurfaceDemoError::PhysicsVelocityFailed; return false; } authority.BeginFrame(); if(!follower.StepGuarded(world,entity,controller,navigation,0.25F,authority) || !world.UpdateTransforms()) { error=NpcRouteAnimationSurfaceDemoError::RouteFailed; return false; } } else if(!bodies.SetDynamicPlanarVelocity(entities,body,0.0F,0.0F)) { error=NpcRouteAnimationSurfaceDemoError::PhysicsVelocityFailed; return false; } if(!physicsBridge.Apply(entities,body,bodies,locomotion,animation)) { error=NpcRouteAnimationSurfaceDemoError::PhysicsBridgeFailed; return false; } if(!animation.Update(1.0F/60.0F) || !animation.Sample(timeline,sampled)) { error=NpcRouteAnimationSurfaceDemoError::AnimationUpdateFailed; return false; } uint32_t frameTint=0U; if(!tintBinding.Resolve(sampled,frameTint)) { error=NpcRouteAnimationSurfaceDemoError::TintBindingFailed; return false; } if(sampled>0.0F) ++routeTintFrames; tintHash=(tintHash^frameTint)*1099511628211ULL; if(!renderer.Clear(kClear)) { error=NpcRouteAnimationSurfaceDemoError::ClearFailed; return false; } SpriteBatch batch; if(!sprites.QueueTinted(world,batch,frameTint) || !batch.Flush(renderer,camera)) { error=NpcRouteAnimationSurfaceDemoError::SpriteFlushFailed; return false; } if(!surface.PumpEvents() || surface.CloseRequested() || !surface.Present(renderer)) { error=NpcRouteAnimationSurfaceDemoError::SurfacePresentFailed; return false; } }
    if(!renderer.WritePpm(config.ppmPath)) { error=NpcRouteAnimationSurfaceDemoError::ArtifactWriteFailed; return false; } const Transform3* final=world.GetTransform(entity); if(final==nullptr) { error=NpcRouteAnimationSurfaceDemoError::TransformFailed; return false; } uint32_t visible=0U; for(uint32_t pixel:renderer.Pixels()) if(pixel!=kClear) ++visible; receipt={config.frames,static_cast<uint32_t>(surface.PresentedFrameCount()),visible,renderer.FrameHash(),final->x,final->z,sampled,follower.ReachedGoal(),locomotion.IsLocomoting(),routeTintFrames,tintHash}; return true;
}
} // namespace NeoEngine
