#include "AudioMixer.h"
#include <algorithm>
#include <cmath>
namespace NeoEngine {
bool AudioMixer::Play(uint32_t id,std::vector<int16_t>s,uint16_t g){if(id==0||s.empty()||s.size()>kMaxSamplesPerVoice||g==0)return false;for(const auto&v:m_Voices)if(v.id==id)return false;if(m_Voices.size()==kMaxVoices)return false;m_Voices.push_back({id,std::move(s),0,g,0.0f,false});return true;}
bool AudioMixer::PlaySpatial(const SpatialVoiceParams&p){if(p.id==0||p.mono.empty()||p.mono.size()>kMaxSamplesPerVoice||p.gainQ8==0)return false;for(const auto&v:m_Voices)if(v.id==p.id)return false;if(m_Voices.size()==kMaxVoices)return false;for(float x:p.position)if(!std::isfinite(x))return false;float dx=p.position[0]-m_Listener.position[0],dy=p.position[1]-m_Listener.position[1],dz=p.position[2]-m_Listener.position[2];float distance=std::sqrt(dx*dx+dy*dy+dz*dz);float minD=std::max(0.001f,p.attenuation.minDistance),maxD=std::max(minD,p.attenuation.maxDistance);float attenuation=1.0f;if(p.spatialized){if(distance>=maxD)attenuation=p.attenuation.minVolume;else if(distance>minD){float t=(distance-minD)/(maxD-minD);attenuation=p.attenuation.model==AudioAttenuationModel::Linear?1.0f-t:1.0f/(1.0f+t*t*(maxD/minD));attenuation=std::max(p.attenuation.minVolume,attenuation);}}float gain=std::clamp(static_cast<float>(p.gainQ8)*attenuation,0.0f,65535.0f);float pan=0.0f;if(p.spatialized&&distance>0.001f)pan=std::clamp(dx/distance,-1.0f,1.0f);m_Voices.push_back({p.id,p.mono,0,static_cast<uint16_t>(gain),pan,p.looping});return true;}
bool AudioMixer::Stop(uint32_t id){auto it=std::find_if(m_Voices.begin(),m_Voices.end(),[&](const auto&v){return v.id==id;});if(it==m_Voices.end())return false;m_Voices.erase(it);return true;}
void AudioMixer::Clear(){m_Voices.clear();}
void AudioMixer::Mix(size_t frames,std::vector<int16_t>&out){out.assign(frames*2,0);for(size_t f=0;f<frames;++f){int64_t l=0,r=0;for(auto&v:m_Voices){if(v.samples.empty())continue;if(v.cursor>=v.samples.size()){if(v.looping)v.cursor=0;else continue;}int64_t s=static_cast<int64_t>(v.samples[v.cursor++])*v.gain/256;float pan=std::clamp(v.pan,-1.0f,1.0f);l+=static_cast<int64_t>(s*(1.0f-pan)*0.5f);r+=static_cast<int64_t>(s*(1.0f+pan)*0.5f);}out[f*2]=static_cast<int16_t>(std::clamp<int64_t>(l,-32768,32767));out[f*2+1]=static_cast<int16_t>(std::clamp<int64_t>(r,-32768,32767));}m_Voices.erase(std::remove_if(m_Voices.begin(),m_Voices.end(),[](const auto&v){return !v.looping&&v.cursor>=v.samples.size();}),m_Voices.end());}
}
