#include "Runtime/EditorSceneDocumentCodec.h"

#include <bit>
#include <cmath>
#include <cstring>
#include <type_traits>

namespace NeoEngine {
namespace {
constexpr uint8_t kMagic[4] = {'F', 'Z', 'S', 'D'};
constexpr uint8_t kCodecVersionV1 = 1;
constexpr uint8_t kCodecVersionV2 = 2;
constexpr uint8_t kCurrentCodecVersion = kCodecVersionV2;

template <typename T> requires std::is_integral_v<T>
void Write(std::vector<uint8_t>& out, T value) { using U=std::make_unsigned_t<T>; U raw=static_cast<U>(value); for(size_t i=0;i<sizeof(T);++i) out.push_back(static_cast<uint8_t>((raw>>(i*8U))&0xFFU)); }
void Write(std::vector<uint8_t>& out,float value){Write<uint32_t>(out,std::bit_cast<uint32_t>(value));}

template <typename T> requires std::is_integral_v<T>
bool Read(const std::vector<uint8_t>& in,size_t& offset,T& value){if(offset>in.size()||in.size()-offset<sizeof(T))return false;using U=std::make_unsigned_t<T>;U raw=0;for(size_t i=0;i<sizeof(T);++i)raw|=static_cast<U>(in[offset+i])<<(i*8U);offset+=sizeof(T);value=static_cast<T>(raw);return true;}
bool Read(const std::vector<uint8_t>& in,size_t& offset,float& value){uint32_t raw=0;if(!Read(in,offset,raw))return false;value=std::bit_cast<float>(raw);return true;}
bool FiniteTransform(const Transform3&t){return std::isfinite(t.x)&&std::isfinite(t.y)&&std::isfinite(t.z)&&std::isfinite(t.rx)&&std::isfinite(t.ry)&&std::isfinite(t.rz)&&std::isfinite(t.sx)&&std::isfinite(t.sy)&&std::isfinite(t.sz);}
bool WriteString(std::vector<uint8_t>&out,const std::string&v){if(v.size()>EditorSceneDocumentCodec::kMaxStringBytes||v.size()>UINT16_MAX)return false;Write<uint16_t>(out,static_cast<uint16_t>(v.size()));out.insert(out.end(),v.begin(),v.end());return true;}
bool ReadString(const std::vector<uint8_t>&in,size_t&offset,std::string&v){uint16_t size=0;if(!Read(in,offset,size)||size>EditorSceneDocumentCodec::kMaxStringBytes||offset>in.size()||in.size()-offset<size)return false;v.assign(reinterpret_cast<const char*>(in.data()+offset),size);offset+=size;return true;}
bool WriteActor(std::vector<uint8_t>&out,const EditorSceneActor&a){if(!FiniteTransform(a.transform)||a.kind>EditorSceneActorKind::Sprite||!std::isfinite(a.spriteWidth)||!std::isfinite(a.spriteHeight))return false;Write<uint32_t>(out,a.id);Write<uint32_t>(out,a.parentId);Write<uint8_t>(out,static_cast<uint8_t>(a.kind));for(float v:{a.transform.x,a.transform.y,a.transform.z,a.transform.rx,a.transform.ry,a.transform.rz,a.transform.sx,a.transform.sy,a.transform.sz})Write(out,v);return WriteString(out,a.name)&&WriteString(out,a.assetId)&&WriteString(out,a.materialAssetId)&&WriteString(out,a.materialName)&&WriteString(out,a.textureAssetId)&&(Write(out,a.spriteWidth),true)&&(Write(out,a.spriteHeight),true)&&(Write(out,a.spriteLayer),true)&&(Write(out,a.spriteOrder),true)&&(Write(out,a.spriteRgba),true);}
bool ReadActor(const std::vector<uint8_t>&in,size_t&offset,EditorSceneActor&a,bool hasName){uint8_t kind=0;if(!Read(in,offset,a.id)||!Read(in,offset,a.parentId)||!Read(in,offset,kind)||kind>static_cast<uint8_t>(EditorSceneActorKind::Sprite))return false;a.kind=static_cast<EditorSceneActorKind>(kind);float* values[]={&a.transform.x,&a.transform.y,&a.transform.z,&a.transform.rx,&a.transform.ry,&a.transform.rz,&a.transform.sx,&a.transform.sy,&a.transform.sz};for(float*v:values)if(!Read(in,offset,*v))return false;if(hasName&&!ReadString(in,offset,a.name))return false;return FiniteTransform(a.transform)&&ReadString(in,offset,a.assetId)&&ReadString(in,offset,a.materialAssetId)&&ReadString(in,offset,a.materialName)&&ReadString(in,offset,a.textureAssetId)&&Read(in,offset,a.spriteWidth)&&Read(in,offset,a.spriteHeight)&&Read(in,offset,a.spriteLayer)&&Read(in,offset,a.spriteOrder)&&Read(in,offset,a.spriteRgba)&&std::isfinite(a.spriteWidth)&&std::isfinite(a.spriteHeight);}
}

bool EditorSceneDocumentCodec::Encode(const EditorSceneDocument&document,std::vector<uint8_t>&bytes){if(document.version<EditorSceneDocument::kMinSupportedVersion||document.version>EditorSceneDocument::kVersion){lastError_=EditorSceneDocumentCodecError::UnsupportedVersion;return false;}if(document.sceneId.empty()||document.sceneId.size()>kMaxStringBytes||document.actors.size()>EditorSceneDocumentAdapter::kMaxActors){lastError_=document.actors.size()>EditorSceneDocumentAdapter::kMaxActors?EditorSceneDocumentCodecError::Capacity:EditorSceneDocumentCodecError::InvalidDocument;return false;}std::vector<uint8_t>candidate;candidate.reserve(128U+document.actors.size()*128U);candidate.insert(candidate.end(),std::begin(kMagic),std::end(kMagic));Write(candidate,kCurrentCodecVersion);Write(candidate,document.version);Write<uint16_t>(candidate,0U);if(!WriteString(candidate,document.sceneId)){lastError_=EditorSceneDocumentCodecError::InvalidString;return false;}Write(candidate,document.revision);Write<uint16_t>(candidate,static_cast<uint16_t>(document.actors.size()));for(const auto&a:document.actors)if(!WriteActor(candidate,a)){lastError_=!FiniteTransform(a.transform)||!std::isfinite(a.spriteWidth)||!std::isfinite(a.spriteHeight)?EditorSceneDocumentCodecError::InvalidTransform:EditorSceneDocumentCodecError::InvalidActorKind;return false;}if(candidate.size()>kMaxBytes){lastError_=EditorSceneDocumentCodecError::Capacity;return false;}bytes=std::move(candidate);lastError_=EditorSceneDocumentCodecError::None;return true;}

bool EditorSceneDocumentCodec::Decode(const std::vector<uint8_t>&bytes,EditorSceneDocument&document){if(bytes.size()>kMaxBytes){lastError_=EditorSceneDocumentCodecError::Capacity;return false;}size_t offset=0;uint8_t magic[4]{};for(auto&v:magic)if(!Read(bytes,offset,v)){lastError_=EditorSceneDocumentCodecError::Truncated;return false;}if(std::memcmp(magic,kMagic,sizeof(kMagic))!=0){lastError_=EditorSceneDocumentCodecError::InvalidFormat;return false;}uint8_t codecVersion=0,documentVersion=0;uint16_t reserved=0;if(!Read(bytes,offset,codecVersion)||!Read(bytes,offset,documentVersion)||!Read(bytes,offset,reserved)){lastError_=EditorSceneDocumentCodecError::Truncated;return false;}if((codecVersion!=kCodecVersionV1&&codecVersion!=kCodecVersionV2)||documentVersion<EditorSceneDocument::kMinSupportedVersion||documentVersion>EditorSceneDocument::kVersion){lastError_=EditorSceneDocumentCodecError::UnsupportedVersion;return false;}EditorSceneDocument candidate{};candidate.version=documentVersion;if(!ReadString(bytes,offset,candidate.sceneId)||candidate.sceneId.empty()||!Read(bytes,offset,candidate.revision)){lastError_=EditorSceneDocumentCodecError::Truncated;return false;}uint16_t actorCount=0;if(!Read(bytes,offset,actorCount)){lastError_=EditorSceneDocumentCodecError::Truncated;return false;}if(actorCount>EditorSceneDocumentAdapter::kMaxActors){lastError_=EditorSceneDocumentCodecError::Capacity;return false;}candidate.actors.reserve(actorCount);for(uint16_t i=0;i<actorCount;++i){EditorSceneActor actor{};if(!ReadActor(bytes,offset,actor,codecVersion==kCodecVersionV2)){lastError_=EditorSceneDocumentCodecError::InvalidFormat;return false;}candidate.actors.push_back(std::move(actor));}if(offset!=bytes.size()){lastError_=EditorSceneDocumentCodecError::TrailingData;return false;}document=std::move(candidate);lastError_=EditorSceneDocumentCodecError::None;return true;}
} // namespace NeoEngine
