#include "MeshRenderer.h"

#include "SoftwareRenderer.h"
#include "TextureStaging.h"

#include <algorithm>
#include <array>
#include <cmath>

namespace NeoEngine {
namespace {
struct WorkingVertex { RenderPoint3 world{}; RenderPoint3 normal{}; float u=0.0F; float v=0.0F; };

bool Finite(RenderPoint3 value){return std::isfinite(value.x)&&std::isfinite(value.y)&&std::isfinite(value.z);}
float Length(RenderPoint3 value){return std::sqrt(value.x*value.x+value.y*value.y+value.z*value.z);}
RenderPoint3 RotateXYZ(RenderPoint3 value,RenderPoint3 rotationRadians){const float cx=std::cos(rotationRadians.x),sx=std::sin(rotationRadians.x),cy=std::cos(rotationRadians.y),sy=std::sin(rotationRadians.y),cz=std::cos(rotationRadians.z),sz=std::sin(rotationRadians.z);const RenderPoint3 xRotated{value.x,value.y*cx-value.z*sx,value.y*sx+value.z*cx};const RenderPoint3 yRotated{xRotated.x*cy+xRotated.z*sy,xRotated.y,-xRotated.x*sy+xRotated.z*cy};return {yRotated.x*cz-yRotated.y*sz,yRotated.x*sz+yRotated.y*cz,yRotated.z};}
uint32_t Lit(uint32_t rgba,float factor){const auto channel=[factor](uint32_t value){return static_cast<uint32_t>(std::clamp(std::lround(static_cast<float>(value)*factor),0L,255L));};return (rgba&0xFF000000U)|(channel((rgba>>16U)&0xFFU)<<16U)|(channel((rgba>>8U)&0xFFU)<<8U)|channel(rgba&0xFFU);}
bool FrontFacing(const RenderPoint3& a,const RenderPoint3& b,const RenderPoint3& c){return (b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x)>1e-6F;}
WorkingVertex Interpolate(const WorkingVertex& a,const WorkingVertex& b,float t){const auto mix=[t](float left,float right){return left+(right-left)*t;};return {{mix(a.world.x,b.world.x),mix(a.world.y,b.world.y),mix(a.world.z,b.world.z)},{mix(a.normal.x,b.normal.x),mix(a.normal.y,b.normal.y),mix(a.normal.z,b.normal.z)},mix(a.u,b.u),mix(a.v,b.v)};}
uint8_t ClipNear(const std::array<WorkingVertex,3>& input,RenderCamera& camera,std::array<WorkingVertex,4>& output){const float plane=camera.Config().nearPlane+1e-4F;uint8_t count=0U;WorkingVertex previous=input[2U];RenderPoint3 previousCamera{};if(!camera.WorldToCamera(previous.world,previousCamera))return 0U;bool previousInside=previousCamera.z>=plane;for(const WorkingVertex& current:input){RenderPoint3 currentCamera{};if(!camera.WorldToCamera(current.world,currentCamera))return 0U;const bool currentInside=currentCamera.z>=plane;if(currentInside!=previousInside){const float delta=currentCamera.z-previousCamera.z;if(!std::isfinite(delta)||std::fabs(delta)<1e-6F)return 0U;const float t=(plane-previousCamera.z)/delta;if(!std::isfinite(t)||t<0.0F||t>1.0F)return 0U;output[count++]=Interpolate(previous,current,t);}if(currentInside)output[count++]=current;previous=current;previousCamera=currentCamera;previousInside=currentInside;}return count;}
bool ToProjected(const WorkingVertex& source,const DirectionalLight& light,float ambient,float directional,RenderCamera& camera,RenderVertex& flat,TexturedRenderVertex& textured){RenderPoint3 clip{};RenderPoint3 cameraSpace{};if(!camera.WorldToCamera(source.world,cameraSpace)||!camera.Project(source.world,clip))return false;const float normalLength=Length(source.normal);if(!std::isfinite(normalLength)||normalLength<1e-6F)return false;const float lightLength=Length(light.directionToLight);const float dot=(source.normal.x*light.directionToLight.x+source.normal.y*light.directionToLight.y+source.normal.z*light.directionToLight.z)/(normalLength*lightLength);const float factor=std::clamp(ambient+directional*light.intensity*std::max(0.0F,dot),0.0F,1.0F);const RenderCameraConfig& config=camera.Config();const float reciprocalDepth=config.mode==RenderCameraMode::Perspective?1.0F/cameraSpace.z:1.0F;if(!std::isfinite(reciprocalDepth)||reciprocalDepth<=0.0F)return false;flat={clip.x,clip.y,clip.z,Lit(0xFFFFFFFFU,factor)};textured={clip.x,clip.y,clip.z,source.u,source.v,factor,reciprocalDepth};return true;}
}

bool MeshRenderer::Draw(const std::vector<MeshVertex>& vertices,const std::vector<uint16_t>& indices,const MeshTransform& transform,const MeshMaterial& material,const DirectionalLight& light,RenderCamera& camera,SoftwareRenderer& renderer){
    if(vertices.empty()||indices.empty()||indices.size()%3U!=0U){lastError_=MeshRenderError::EmptyMesh;return false;}
    if(vertices.size()>kMaxVertices||indices.size()>kMaxIndices){lastError_=MeshRenderError::Capacity;return false;}
    if(!Finite(transform.translation)||!Finite(transform.rotationRadians)||!std::isfinite(transform.uniformScale)||transform.uniformScale<=0.0F||!std::isfinite(material.ambient)||!std::isfinite(material.directional)||material.ambient<0.0F||material.directional<0.0F){lastError_=MeshRenderError::InvalidTransform;return false;}
    const bool textured=material.texture!=nullptr;
    if(textured&&(material.texture->assetId.empty()||material.texture->sourceHash==0U||material.texture->width==0U||material.texture->height==0U||material.texture->rgba.size()!=static_cast<size_t>(material.texture->width)*material.texture->height*4U)){lastError_=MeshRenderError::InvalidTexture;return false;}
    if(!Finite(light.directionToLight)||Length(light.directionToLight)<1e-6F||!std::isfinite(light.intensity)||light.intensity<0.0F||light.intensity>8.0F){lastError_=MeshRenderError::InvalidLight;return false;}
    std::vector<WorkingVertex> transformed;transformed.reserve(vertices.size());
    for(const MeshVertex& vertex:vertices){if(!Finite(vertex.position)||!Finite(vertex.normal)||Length(vertex.normal)<1e-6F||!std::isfinite(vertex.u)||!std::isfinite(vertex.v)||vertex.u<0.0F||vertex.u>1.0F||vertex.v<0.0F||vertex.v>1.0F){lastError_=MeshRenderError::InvalidTransform;return false;}const RenderPoint3 rotatedPosition=RotateXYZ({vertex.position.x*transform.uniformScale,vertex.position.y*transform.uniformScale,vertex.position.z*transform.uniformScale},transform.rotationRadians);transformed.push_back({{rotatedPosition.x+transform.translation.x,rotatedPosition.y+transform.translation.y,rotatedPosition.z+transform.translation.z},RotateXYZ(vertex.normal,transform.rotationRadians),vertex.u,vertex.v});}
    for(uint16_t index:indices)if(index>=vertices.size()){lastError_=MeshRenderError::InvalidIndex;return false;}
    for(size_t offset=0;offset<indices.size();offset+=3U){std::array<WorkingVertex,3> input{transformed[indices[offset]],transformed[indices[offset+1U]],transformed[indices[offset+2U]]};std::array<WorkingVertex,4> clipped{};const uint8_t count=ClipNear(input,camera,clipped);if(count<3U)continue;for(uint8_t triangle=1U;triangle+1U<count;++triangle){std::array<RenderVertex,3> flat{};std::array<TexturedRenderVertex,3> texturedVertices{};std::array<RenderPoint3,3> clips{};for(uint8_t point=0U;point<3U;++point){const WorkingVertex& source=point==0U?clipped[0U]:point==1U?clipped[triangle]:clipped[triangle+1U];if(!ToProjected(source,light,material.ambient,material.directional,camera,flat[point],texturedVertices[point])){lastError_=MeshRenderError::ProjectionFailed;return false;}clips[point]={flat[point].x,flat[point].y,flat[point].z};}if(material.cullBackFaces&&!FrontFacing(clips[0U],clips[1U],clips[2U]))continue;const bool drawn=textured?renderer.DrawTexturedTriangle(texturedVertices[0U],texturedVertices[1U],texturedVertices[2U],material.texture->rgba,material.texture->width,material.texture->height,material.rgba):renderer.DrawTriangle({flat[0U].x,flat[0U].y,flat[0U].z,Lit(material.rgba,texturedVertices[0U].light)},{flat[1U].x,flat[1U].y,flat[1U].z,Lit(material.rgba,texturedVertices[1U].light)},{flat[2U].x,flat[2U].y,flat[2U].z,Lit(material.rgba,texturedVertices[2U].light)});if(!drawn){lastError_=MeshRenderError::RasterFailed;return false;}}}
    lastError_=MeshRenderError::None;return true;
}
} // namespace NeoEngine
