#include "RuntimePersistence.h"

#include <algorithm>
#include <array>
#include <cctype>
#include <new>

namespace NeoEngine {
namespace {
constexpr uint32_t kSettingsMagic=0x31545346U, kSaveMagic=0x31565346U;
uint64_t Hash(const std::vector<uint8_t>& bytes) { uint64_t hash=1469598103934665603ULL; for(uint8_t byte:bytes){hash^=byte;hash*=1099511628211ULL;}return hash; }
void U16(std::vector<uint8_t>& out,uint16_t value){out.push_back(static_cast<uint8_t>(value));out.push_back(static_cast<uint8_t>(value>>8U));}
void U32(std::vector<uint8_t>& out,uint32_t value){for(uint8_t shift=0;shift<4;++shift)out.push_back(static_cast<uint8_t>(value>>(shift*8U)));}
void U64(std::vector<uint8_t>& out,uint64_t value){for(uint8_t shift=0;shift<8;++shift)out.push_back(static_cast<uint8_t>(value>>(shift*8U)));}
bool ReadU16(const std::vector<uint8_t>& in,size_t& offset,uint16_t& value){if(offset>in.size()||in.size()-offset<2U)return false;value=static_cast<uint16_t>(in[offset])|static_cast<uint16_t>(in[offset+1U])<<8U;offset+=2U;return true;}
bool ReadU32(const std::vector<uint8_t>& in,size_t& offset,uint32_t& value){if(offset>in.size()||in.size()-offset<4U)return false;value=0;for(uint8_t shift=0;shift<4;++shift)value|=static_cast<uint32_t>(in[offset+shift])<<(shift*8U);offset+=4U;return true;}
bool ReadU64(const std::vector<uint8_t>& in,size_t& offset,uint64_t& value){if(offset>in.size()||in.size()-offset<8U)return false;value=0;for(uint8_t shift=0;shift<8;++shift)value|=static_cast<uint64_t>(in[offset+shift])<<(shift*8U);offset+=8U;return true;}
bool Sensitive(std::string_view text){static constexpr std::array<std::string_view,6> markers{"token","secret","password","credential","apikey","bearer"};std::string lower;lower.reserve(text.size());for(unsigned char c:text)lower.push_back(static_cast<char>(std::tolower(c)));return std::any_of(markers.begin(),markers.end(),[&lower](std::string_view marker){return lower.find(marker)!=std::string::npos;});}
bool ValidKey(std::string_view key){if(key.empty()||key.size()>RuntimeSettingsStore::kMaxKeyBytes)return false;return std::all_of(key.begin(),key.end(),[](unsigned char c){return std::isalnum(c)||c=='-'||c=='_'||c=='.';});}
bool ReadText(const std::vector<uint8_t>& bytes,size_t& offset,size_t length,std::string& value){if(offset>bytes.size()||length>bytes.size()-offset)return false;value.assign(reinterpret_cast<const char*>(bytes.data()+offset),length);offset+=length;return true;}
}
bool RuntimeSettingsStore::Set(std::string key,std::string value){if(!ValidKey(key)){lastError_=RuntimePersistenceError::InvalidKey;return false;}if(value.size()>kMaxValueBytes){lastError_=RuntimePersistenceError::InvalidValue;return false;}if(Sensitive(key)||Sensitive(value)){lastError_=RuntimePersistenceError::SensitiveContent;return false;}const auto found=std::find_if(entries_.begin(),entries_.end(),[&key](const Entry& entry){return entry.key==key;});if(found!=entries_.end()){found->value=std::move(value);lastError_=RuntimePersistenceError::None;return true;}if(entries_.size()>=kMaxEntries){lastError_=RuntimePersistenceError::Capacity;return false;}try{entries_.push_back({std::move(key),std::move(value)});}catch(const std::bad_alloc&){lastError_=RuntimePersistenceError::Capacity;return false;}lastError_=RuntimePersistenceError::None;return true;}
const std::string* RuntimeSettingsStore::Find(std::string_view key) const {const auto found=std::find_if(entries_.begin(),entries_.end(),[key](const Entry& entry){return entry.key==key;});return found==entries_.end()?nullptr:&found->value;}
bool RuntimeSettingsStore::Serialize(std::vector<uint8_t>& out) const {try{std::vector<Entry> ordered=entries_;std::sort(ordered.begin(),ordered.end(),[](const Entry&a,const Entry&b){return a.key<b.key;});std::vector<uint8_t> encoded;encoded.reserve(14U+entries_.size()*4U);U32(encoded,kSettingsMagic);encoded.push_back(kVersion);encoded.push_back(static_cast<uint8_t>(ordered.size()));for(const Entry& entry:ordered){encoded.push_back(static_cast<uint8_t>(entry.key.size()));U16(encoded,static_cast<uint16_t>(entry.value.size()));encoded.insert(encoded.end(),entry.key.begin(),entry.key.end());encoded.insert(encoded.end(),entry.value.begin(),entry.value.end());}U64(encoded,Hash(encoded));out=std::move(encoded);return true;}catch(const std::bad_alloc&){return false;}}
bool RuntimeSettingsStore::Deserialize(const std::vector<uint8_t>& bytes){try{if(bytes.size()<14U){lastError_=RuntimePersistenceError::Corrupt;return false;}size_t offset=0;uint32_t magic=0;if(!ReadU32(bytes,offset,magic)||magic!=kSettingsMagic){lastError_=RuntimePersistenceError::Corrupt;return false;}if(offset>=bytes.size()||bytes[offset++]!=kVersion){lastError_=RuntimePersistenceError::UnsupportedVersion;return false;}if(offset>=bytes.size()){lastError_=RuntimePersistenceError::Corrupt;return false;}const uint8_t count=bytes[offset++];if(count>kMaxEntries){lastError_=RuntimePersistenceError::Capacity;return false;}std::vector<Entry> parsed;parsed.reserve(count);for(uint8_t i=0;i<count;++i){if(offset>=bytes.size()){lastError_=RuntimePersistenceError::Corrupt;return false;}const uint8_t keyLength=bytes[offset++];uint16_t valueLength=0;std::string key,value;if(!ReadU16(bytes,offset,valueLength)||keyLength==0U||keyLength>kMaxKeyBytes||valueLength>kMaxValueBytes||!ReadText(bytes,offset,keyLength,key)||!ReadText(bytes,offset,valueLength,value)||!ValidKey(key)){lastError_=RuntimePersistenceError::Corrupt;return false;}if(Sensitive(key)||Sensitive(value)){lastError_=RuntimePersistenceError::SensitiveContent;return false;}if(std::any_of(parsed.begin(),parsed.end(),[&key](const Entry& entry){return entry.key==key;})){lastError_=RuntimePersistenceError::Corrupt;return false;}parsed.push_back({std::move(key),std::move(value)});}uint64_t expected=0;if(!ReadU64(bytes,offset,expected)){lastError_=RuntimePersistenceError::Corrupt;return false;}if(offset!=bytes.size()){lastError_=RuntimePersistenceError::TrailingBytes;return false;}std::vector<uint8_t> content(bytes.begin(),bytes.end()-8);if(Hash(content)!=expected){lastError_=RuntimePersistenceError::ChecksumMismatch;return false;}entries_=std::move(parsed);lastError_=RuntimePersistenceError::None;return true;}catch(const std::bad_alloc&){lastError_=RuntimePersistenceError::Capacity;return false;}}
bool RuntimeSaveCodec::Serialize(const RuntimeSaveEnvelope& envelope,std::vector<uint8_t>& out,RuntimePersistenceError& error){if(!ValidKey(envelope.kind)||envelope.kind.size()>kMaxKindBytes){error=RuntimePersistenceError::InvalidKey;return false;}if(envelope.payload.size()>kMaxPayloadBytes){error=RuntimePersistenceError::PayloadLimit;return false;}const std::string text(reinterpret_cast<const char*>(envelope.payload.data()),envelope.payload.size());if(Sensitive(envelope.kind)||Sensitive(text)){error=RuntimePersistenceError::SensitiveContent;return false;}try{std::vector<uint8_t> encoded;encoded.reserve(26U+envelope.kind.size()+envelope.payload.size());U32(encoded,kSaveMagic);encoded.push_back(kVersion);encoded.push_back(static_cast<uint8_t>(envelope.kind.size()));U64(encoded,envelope.revision);U32(encoded,static_cast<uint32_t>(envelope.payload.size()));encoded.insert(encoded.end(),envelope.kind.begin(),envelope.kind.end());encoded.insert(encoded.end(),envelope.payload.begin(),envelope.payload.end());U64(encoded,Hash(encoded));out=std::move(encoded);error=RuntimePersistenceError::None;return true;}catch(const std::bad_alloc&){error=RuntimePersistenceError::Capacity;return false;}}
bool RuntimeSaveCodec::Deserialize(const std::vector<uint8_t>& bytes,RuntimeSaveEnvelope& envelope,RuntimePersistenceError& error){
try{
if(bytes.size()<26U){error=RuntimePersistenceError::Corrupt;return false;}
size_t offset=0;uint32_t magic=0;
if(!ReadU32(bytes,offset,magic)||magic!=kSaveMagic){error=RuntimePersistenceError::Corrupt;return false;}
if(offset>=bytes.size()||bytes[offset++]!=kVersion){error=RuntimePersistenceError::UnsupportedVersion;return false;}
if(offset>=bytes.size()){error=RuntimePersistenceError::Corrupt;return false;}
const uint8_t kindLength=bytes[offset++];uint64_t revision=0;uint32_t payloadLength=0;std::string kind;
if(kindLength==0U||kindLength>kMaxKindBytes||!ReadU64(bytes,offset,revision)||!ReadU32(bytes,offset,payloadLength)||payloadLength>kMaxPayloadBytes||!ReadText(bytes,offset,kindLength,kind)||!ValidKey(kind)||offset>bytes.size()||bytes.size()-offset<8U||payloadLength>bytes.size()-offset-8U){error=RuntimePersistenceError::Corrupt;return false;}
const size_t expectedSize=offset+static_cast<size_t>(payloadLength)+8U;
if(bytes.size()<expectedSize){error=RuntimePersistenceError::Corrupt;return false;}
if(bytes.size()>expectedSize){error=RuntimePersistenceError::TrailingBytes;return false;}
std::vector<uint8_t> payload(bytes.begin()+static_cast<std::ptrdiff_t>(offset),bytes.begin()+static_cast<std::ptrdiff_t>(offset+payloadLength));offset+=payloadLength;
uint64_t expected=0;if(!ReadU64(bytes,offset,expected)){error=RuntimePersistenceError::Corrupt;return false;}
std::vector<uint8_t> content(bytes.begin(),bytes.end()-8);if(Hash(content)!=expected){error=RuntimePersistenceError::ChecksumMismatch;return false;}
const std::string text(reinterpret_cast<const char*>(payload.data()),payload.size());if(Sensitive(kind)||Sensitive(text)){error=RuntimePersistenceError::SensitiveContent;return false;}
envelope={std::move(kind),revision,std::move(payload)};error=RuntimePersistenceError::None;return true;
}catch(const std::bad_alloc&){error=RuntimePersistenceError::Capacity;return false;}}

} // namespace NeoEngine
