#include "Runtime/SceneSpriteAdapter.h"

#include <algorithm>
#include <cmath>

namespace NeoEngine {
namespace { bool ValidTexture(const CpuTextureResource& texture) { return !texture.assetId.empty() && texture.sourceHash != 0U && texture.width > 0U && texture.height > 0U && texture.rgba.size() == static_cast<size_t>(texture.width) * texture.height * 4U; } uint8_t MultiplyChannel(uint32_t left,uint32_t right,uint32_t shift){return static_cast<uint8_t>(((((left>>shift)&0xFFU)*((right>>shift)&0xFFU))+127U)/255U);} uint32_t MultiplyRgba(uint32_t left,uint32_t right){return (static_cast<uint32_t>(MultiplyChannel(left,right,24U))<<24U)|(static_cast<uint32_t>(MultiplyChannel(left,right,16U))<<16U)|(static_cast<uint32_t>(MultiplyChannel(left,right,8U))<<8U)|static_cast<uint32_t>(MultiplyChannel(left,right,0U));} }
bool SceneSpriteAdapter::Fail(SceneSpriteAdapterError error) const { lastError_ = error; return false; }
bool SceneSpriteAdapter::AddStaged(SceneEntity entity, const CpuTextureResource& texture, float width, float height, int16_t layer, int16_t order, uint32_t rgba, float rotationRadians, bool faceCamera, bool depthWrite, uint16_t sourceX, uint16_t sourceY, uint16_t sourceWidth, uint16_t sourceHeight) { if (instances_.size() >= kMaxInstances) return Fail(SceneSpriteAdapterError::Capacity); const bool full=sourceWidth==0U&&sourceHeight==0U; const bool validRect=full?sourceX==0U&&sourceY==0U:(sourceWidth!=0U&&sourceHeight!=0U&&sourceX<texture.width&&sourceY<texture.height&&static_cast<uint32_t>(sourceX)+sourceWidth<=texture.width&&static_cast<uint32_t>(sourceY)+sourceHeight<=texture.height); if (!ValidTexture(texture) || !validRect || !std::isfinite(width) || !std::isfinite(height) || !std::isfinite(rotationRadians) || width <= 0.0F || height <= 0.0F) return Fail(SceneSpriteAdapterError::InvalidResource); for (const Instance& instance : instances_) if (instance.entity == entity) return Fail(SceneSpriteAdapterError::DuplicateEntity); instances_.push_back({entity, texture, width, height, layer, order, rgba, rotationRadians, faceCamera, depthWrite, sourceX, sourceY, sourceWidth, sourceHeight}); lastError_ = SceneSpriteAdapterError::None; return true; }
bool SceneSpriteAdapter::RefreshStaged(SceneEntity entity, const CpuTextureResource& texture) { auto found=std::find_if(instances_.begin(),instances_.end(),[entity](const Instance& instance){return instance.entity==entity;}); if(found==instances_.end())return Fail(SceneSpriteAdapterError::MissingEntity); const bool full=found->sourceWidth==0U&&found->sourceHeight==0U; const bool validRect=full?found->sourceX==0U&&found->sourceY==0U:(found->sourceWidth!=0U&&found->sourceHeight!=0U&&found->sourceX<texture.width&&found->sourceY<texture.height&&static_cast<uint32_t>(found->sourceX)+found->sourceWidth<=texture.width&&static_cast<uint32_t>(found->sourceY)+found->sourceHeight<=texture.height); if(!ValidTexture(texture)||!validRect)return Fail(SceneSpriteAdapterError::InvalidResource); found->texture=texture; lastError_=SceneSpriteAdapterError::None; return true; }
bool SceneSpriteAdapter::Queue(const SceneWorld& world, SpriteBatch& batch) const { return QueueTinted(world, batch, 0xFFFFFFFFU); }
bool SceneSpriteAdapter::QueueTinted(const SceneWorld& world, SpriteBatch& batch, uint32_t frameRgba) const { for (const Instance& instance : instances_) { const Transform3* transform = world.GetTransform(instance.entity); if (transform == nullptr) return Fail(SceneSpriteAdapterError::MissingTransform); if (!batch.Queue({transform->x, transform->y, transform->z, instance.width * transform->sx, instance.height * transform->sy, instance.layer, instance.order, MultiplyRgba(instance.rgba,frameRgba), &instance.texture, transform->rz + instance.rotationRadians, instance.faceCamera, instance.depthWrite, instance.sourceX, instance.sourceY, instance.sourceWidth, instance.sourceHeight})) return Fail(SceneSpriteAdapterError::QueueRejected); } lastError_ = SceneSpriteAdapterError::None; return true; }
bool SceneSpriteAdapter::QueueFrame(const SceneWorld& world, SpriteBatch& batch, SpriteSourceRect sourceRect, uint32_t frameRgba) const { if(sourceRect.width==0U||sourceRect.height==0U)return Fail(SceneSpriteAdapterError::InvalidResource); for (const Instance& instance : instances_) { const Transform3* transform = world.GetTransform(instance.entity); if (transform == nullptr) return Fail(SceneSpriteAdapterError::MissingTransform); if (!batch.Queue({transform->x, transform->y, transform->z, instance.width * transform->sx, instance.height * transform->sy, instance.layer, instance.order, MultiplyRgba(instance.rgba,frameRgba), &instance.texture, transform->rz + instance.rotationRadians, instance.faceCamera, instance.depthWrite, sourceRect.x, sourceRect.y, sourceRect.width, sourceRect.height})) return Fail(SceneSpriteAdapterError::QueueRejected); } lastError_ = SceneSpriteAdapterError::None; return true; }
void SceneSpriteAdapter::Clear() { instances_.clear(); lastError_ = SceneSpriteAdapterError::None; }
} // namespace NeoEngine
