#include "SpriteBatch.h"

#include "SoftwareRenderer.h"
#include "TextureStaging.h"

#include <algorithm>
#include <cmath>

namespace NeoEngine {
namespace { bool ValidTexture(const CpuTextureResource& texture) { return !texture.assetId.empty() && texture.sourceHash != 0U && texture.width > 0U && texture.height > 0U && texture.rgba.size() == static_cast<size_t>(texture.width) * texture.height * 4U; } }
bool SpriteBatch::Queue(SpriteDraw draw) { if (sprites_.size() >= kMaxSprites) { lastError_ = SpriteBatchError::Capacity; return false; } if (!(draw.width > 0.0F) || !(draw.height > 0.0F) || !std::isfinite(draw.x) || !std::isfinite(draw.y) || !std::isfinite(draw.z) || !std::isfinite(draw.width) || !std::isfinite(draw.height) || (draw.texture != nullptr && !ValidTexture(*draw.texture))) { lastError_ = SpriteBatchError::InvalidSize; return false; } sprites_.push_back({draw, sequence_++}); lastError_ = SpriteBatchError::None; return true; }
bool SpriteBatch::Flush(SoftwareRenderer& renderer, RenderCamera& camera) { std::stable_sort(sprites_.begin(), sprites_.end(), [](const Pending& a, const Pending& b) { return a.draw.layer != b.draw.layer ? a.draw.layer < b.draw.layer : (a.draw.order != b.draw.order ? a.draw.order < b.draw.order : a.sequence < b.sequence); }); for (const Pending& pending : sprites_) { const SpriteDraw& draw = pending.draw; const float hx = draw.width * 0.5F, hy = draw.height * 0.5F; RenderPoint3 a{}, b{}, c{}, d{}; if (!camera.Project({draw.x-hx, draw.y-hy, draw.z}, a) || !camera.Project({draw.x+hx, draw.y-hy, draw.z}, b) || !camera.Project({draw.x+hx, draw.y+hy, draw.z}, c) || !camera.Project({draw.x-hx, draw.y+hy, draw.z}, d)) { lastError_ = SpriteBatchError::ProjectionFailed; return false; } bool drawn = false; if (draw.texture == nullptr) { const RenderVertex va{a.x,a.y,a.z,draw.rgba}, vb{b.x,b.y,b.z,draw.rgba}, vc{c.x,c.y,c.z,draw.rgba}, vd{d.x,d.y,d.z,draw.rgba}; drawn = renderer.DrawTriangle(va,vb,vc,true) && renderer.DrawTriangle(va,vc,vd,true); } else { const float reciprocalDepth = camera.Config().mode == RenderCameraMode::Perspective ? 1.0F / (draw.z - camera.Config().position.z) : 1.0F; if (!std::isfinite(reciprocalDepth) || reciprocalDepth <= 0.0F) { lastError_ = SpriteBatchError::ProjectionFailed; return false; } const TexturedRenderVertex va{a.x,a.y,a.z,0.0F,0.0F,1.0F,reciprocalDepth}, vb{b.x,b.y,b.z,1.0F,0.0F,1.0F,reciprocalDepth}, vc{c.x,c.y,c.z,1.0F,1.0F,1.0F,reciprocalDepth}, vd{d.x,d.y,d.z,0.0F,1.0F,1.0F,reciprocalDepth}; drawn = renderer.DrawTexturedTriangle(va,vb,vc,draw.texture->rgba,draw.texture->width,draw.texture->height,draw.rgba,true) && renderer.DrawTexturedTriangle(va,vc,vd,draw.texture->rgba,draw.texture->width,draw.texture->height,draw.rgba,true); } if (!drawn) { lastError_ = SpriteBatchError::DrawFailed; return false; } } lastError_ = SpriteBatchError::None; return true; }
void SpriteBatch::Clear() { sprites_.clear(); sequence_ = 0; lastError_ = SpriteBatchError::None; }
} // namespace NeoEngine
