#include "SpriteBatch.h"

#include "SoftwareRenderer.h"
#include "TextureStaging.h"

#include <algorithm>
#include <array>
#include <cmath>

namespace NeoEngine {
namespace {
constexpr uint8_t kMaxClippedVertices=10U;
enum class FrustumPlane : uint8_t { Left, Right, Bottom, Top, Near, Far };
struct SpriteVertex { RenderPoint3 world{}; float u=0.0F; float v=0.0F; };
bool ValidTexture(const CpuTextureResource& texture) { return !texture.assetId.empty() && texture.sourceHash != 0U && texture.width > 0U && texture.height > 0U && texture.rgba.size() == static_cast<size_t>(texture.width) * texture.height * 4U; }
SpriteVertex Interpolate(const SpriteVertex& a,const SpriteVertex& b,float t){const auto mix=[t](float left,float right){return left+(right-left)*t;};return {{mix(a.world.x,b.world.x),mix(a.world.y,b.world.y),mix(a.world.z,b.world.z)},mix(a.u,b.u),mix(a.v,b.v)};}
bool PlaneDistance(const SpriteVertex& vertex,FrustumPlane plane,RenderCamera& camera,float& distance){RenderPoint3 view{};if(!camera.WorldToCamera(vertex.world,view))return false;const RenderCameraConfig& config=camera.Config();constexpr float epsilon=1e-4F;const float halfHeight=config.mode==RenderCameraMode::Perspective?view.z*std::tan(config.verticalFovDegrees*0.00872664626F):config.orthographicHalfHeight;const float halfWidth=halfHeight*config.aspect;switch(plane){case FrustumPlane::Left:distance=view.x+halfWidth-epsilon;break;case FrustumPlane::Right:distance=halfWidth-view.x-epsilon;break;case FrustumPlane::Bottom:distance=view.y+halfHeight-epsilon;break;case FrustumPlane::Top:distance=halfHeight-view.y-epsilon;break;case FrustumPlane::Near:distance=view.z-config.nearPlane-epsilon;break;case FrustumPlane::Far:distance=config.farPlane-view.z-epsilon;break;}return std::isfinite(distance);}
uint8_t ClipPlane(const std::array<SpriteVertex,kMaxClippedVertices>& input,uint8_t inputCount,FrustumPlane plane,RenderCamera& camera,std::array<SpriteVertex,kMaxClippedVertices>& output){if(inputCount==0U||inputCount>kMaxClippedVertices)return 0U;uint8_t count=0U;SpriteVertex previous=input[inputCount-1U];float previousDistance=0.0F;if(!PlaneDistance(previous,plane,camera,previousDistance))return 0U;bool previousInside=previousDistance>=0.0F;for(uint8_t index=0U;index<inputCount;++index){const SpriteVertex& current=input[index];float currentDistance=0.0F;if(!PlaneDistance(current,plane,camera,currentDistance))return 0U;const bool currentInside=currentDistance>=0.0F;if(currentInside!=previousInside){const float denominator=previousDistance-currentDistance;if(!std::isfinite(denominator)||std::fabs(denominator)<1e-6F)return 0U;const float t=previousDistance/denominator;if(!std::isfinite(t)||t<0.0F||t>1.0F||count>=kMaxClippedVertices)return 0U;output[count++]=Interpolate(previous,current,t);}if(currentInside){if(count>=kMaxClippedVertices)return 0U;output[count++]=current;}previous=current;previousDistance=currentDistance;previousInside=currentInside;}return count;}
uint8_t ClipFrustum(const std::array<SpriteVertex,4>& input,RenderCamera& camera,std::array<SpriteVertex,kMaxClippedVertices>& output){std::array<SpriteVertex,kMaxClippedVertices> first{};std::array<SpriteVertex,kMaxClippedVertices> second{};for(uint8_t index=0U;index<4U;++index)first[index]=input[index];uint8_t count=4U;for(const FrustumPlane plane:{FrustumPlane::Near,FrustumPlane::Far,FrustumPlane::Left,FrustumPlane::Right,FrustumPlane::Bottom,FrustumPlane::Top}){count=ClipPlane(first,count,plane,camera,second);if(count<3U)return count;first=second;}output=first;return count;}
} // namespace
bool SpriteBatch::Queue(SpriteDraw draw) { if (sprites_.size() >= kMaxSprites) { lastError_ = SpriteBatchError::Capacity; return false; } if (!(draw.width > 0.0F) || !(draw.height > 0.0F) || !std::isfinite(draw.x) || !std::isfinite(draw.y) || !std::isfinite(draw.z) || !std::isfinite(draw.width) || !std::isfinite(draw.height) || (draw.texture != nullptr && !ValidTexture(*draw.texture))) { lastError_ = SpriteBatchError::InvalidSize; return false; } sprites_.push_back({draw, sequence_++}); lastError_ = SpriteBatchError::None; return true; }
bool SpriteBatch::Flush(SoftwareRenderer& renderer, RenderCamera& camera) {
    std::stable_sort(sprites_.begin(), sprites_.end(), [](const Pending& a, const Pending& b) { return a.draw.layer != b.draw.layer ? a.draw.layer < b.draw.layer : (a.draw.order != b.draw.order ? a.draw.order < b.draw.order : a.sequence < b.sequence); });
    SoftwareRenderer candidate = renderer;
    for (const Pending& pending : sprites_) { const SpriteDraw& draw = pending.draw; const float hx = draw.width * 0.5F, hy = draw.height * 0.5F; const std::array<SpriteVertex,4> input{{{{draw.x-hx,draw.y-hy,draw.z},0.0F,0.0F},{{draw.x+hx,draw.y-hy,draw.z},1.0F,0.0F},{{draw.x+hx,draw.y+hy,draw.z},1.0F,1.0F},{{draw.x-hx,draw.y+hy,draw.z},0.0F,1.0F}}};std::array<SpriteVertex,kMaxClippedVertices> clipped{};const uint8_t count=ClipFrustum(input,camera,clipped);if(count<3U)continue;for(uint8_t triangle=1U;triangle+1U<count;++triangle){std::array<RenderPoint3,3> points{};std::array<float,3> reciprocalDepth{};const std::array<const SpriteVertex*,3> source{{&clipped[0U],&clipped[triangle],&clipped[triangle+1U]}};for(uint8_t point=0U;point<3U;++point){if(!camera.Project(source[point]->world,points[point])){lastError_=SpriteBatchError::ProjectionFailed;return false;}RenderPoint3 view{};if(!camera.WorldToCamera(source[point]->world,view)){lastError_=SpriteBatchError::ProjectionFailed;return false;}reciprocalDepth[point]=camera.Config().mode==RenderCameraMode::Perspective?1.0F/view.z:1.0F;if(!std::isfinite(reciprocalDepth[point])||reciprocalDepth[point]<=0.0F){lastError_=SpriteBatchError::ProjectionFailed;return false;}}const bool drawn=draw.texture==nullptr?candidate.DrawTriangle({points[0].x,points[0].y,points[0].z,draw.rgba},{points[1].x,points[1].y,points[1].z,draw.rgba},{points[2].x,points[2].y,points[2].z,draw.rgba},true):candidate.DrawTexturedTriangle({points[0].x,points[0].y,points[0].z,source[0]->u,source[0]->v,1.0F,reciprocalDepth[0]},{points[1].x,points[1].y,points[1].z,source[1]->u,source[1]->v,1.0F,reciprocalDepth[1]},{points[2].x,points[2].y,points[2].z,source[2]->u,source[2]->v,1.0F,reciprocalDepth[2]},draw.texture->rgba,draw.texture->width,draw.texture->height,draw.rgba,true);if(!drawn){lastError_=SpriteBatchError::DrawFailed;return false;}} }
    renderer = std::move(candidate);
    lastError_ = SpriteBatchError::None;
    return true;
}
void SpriteBatch::Clear() { sprites_.clear(); sequence_ = 0; lastError_ = SpriteBatchError::None; }
} // namespace NeoEngine
