#include "TransformAnimationBinding.h"

#include <cmath>
#include <memory>
#include <new>

namespace NeoEngine {
bool TransformAnimationBinding::Add(const TransformAnimationSpec& spec) { if(spec.entity.index==0xFFFFU||spec.trackId.empty()||spec.trackId.find('\0')!=std::string::npos||spec.trackId.size()>64U||static_cast<uint8_t>(spec.channel)>static_cast<uint8_t>(TransformChannel::ScaleZ)||!std::isfinite(spec.multiplier)||!std::isfinite(spec.offset)){lastError_=TransformAnimationError::InvalidBinding;return false;} if(bindings_.size()>=kMaxBindings){lastError_=TransformAnimationError::Capacity;return false;} try{bindings_.push_back(spec);}catch(const std::bad_alloc&){lastError_=TransformAnimationError::Capacity;return false;} lastError_=TransformAnimationError::None;return true; }
bool TransformAnimationBinding::Apply(SceneWorld& world,const AnimationTimeline& timeline,float time,AnimationPlayback playback) { if(!std::isfinite(time)){lastError_=TransformAnimationError::InvalidBinding;return false;} std::unique_ptr<SceneWorld> candidate;try{candidate=std::make_unique<SceneWorld>(world);}catch(const std::bad_alloc&){lastError_=TransformAnimationError::TransformFailed;return false;} for(const TransformAnimationSpec& spec:bindings_){const Transform3* local=candidate->GetLocalTransform(spec.entity);if(!local){lastError_=TransformAnimationError::MissingEntity;return false;}float sample=0.0F;if(!timeline.Sample(spec.trackId,time,playback,sample)){lastError_=timeline.LastError()==AnimationError::MissingTrack?TransformAnimationError::MissingTrack:TransformAnimationError::SampleFailed;return false;}const double calculated=static_cast<double>(sample)*static_cast<double>(spec.multiplier)+static_cast<double>(spec.offset);const float value=static_cast<float>(calculated);if(!std::isfinite(value)){lastError_=TransformAnimationError::SampleFailed;return false;}Transform3 next=*local;switch(spec.channel){case TransformChannel::PositionX:next.x=value;break;case TransformChannel::PositionY:next.y=value;break;case TransformChannel::PositionZ:next.z=value;break;case TransformChannel::RotationX:next.rx=value;break;case TransformChannel::RotationY:next.ry=value;break;case TransformChannel::RotationZ:next.rz=value;break;case TransformChannel::ScaleX:next.sx=value;break;case TransformChannel::ScaleY:next.sy=value;break;case TransformChannel::ScaleZ:next.sz=value;break;default:lastError_=TransformAnimationError::InvalidBinding;return false;}if(!candidate->SetTransform(spec.entity,next)){lastError_=TransformAnimationError::TransformFailed;return false;}}world=*candidate;lastError_=TransformAnimationError::None;return true; }
} // namespace NeoEngine
