#include "UiInputRouter.h"

#include <algorithm>
#include <cmath>

namespace NeoEngine {
bool UiInputRouter::HasWidget(uint16_t id) const { return std::any_of(widgets_.begin(),widgets_.end(),[id](const Widget& widget){return widget.spec.id==id;}); }
bool UiInputRouter::IsFocusable(uint16_t id) const { const auto found=std::find_if(widgets_.begin(),widgets_.end(),[id](const Widget& widget){return widget.spec.id==id;});return found!=widgets_.end()&&found->spec.visible&&found->spec.interactive&&found->spec.focusable; }
bool UiInputRouter::AddWidget(const UiWidgetSpec& spec) { if(spec.id==0U||HasWidget(spec.id)){lastError_=spec.id==0U?UiError::InvalidWidget:UiError::DuplicateWidget;return false;} if(widgets_.size()>=kMaxWidgets){lastError_=UiError::Capacity;return false;} if(spec.parentId!=0U&&!HasWidget(spec.parentId)){lastError_=UiError::MissingParent;return false;} if(!std::isfinite(spec.rect.x)||!std::isfinite(spec.rect.y)||!std::isfinite(spec.rect.width)||!std::isfinite(spec.rect.height)||spec.rect.width<=0.0F||spec.rect.height<=0.0F){lastError_=UiError::InvalidRect;return false;} widgets_.push_back({spec,sequence_++});lastError_=UiError::None;return true; }
bool UiInputRouter::RemoveWidget(uint16_t id) { const auto found=std::find_if(widgets_.begin(),widgets_.end(),[id](const Widget& widget){return widget.spec.id==id;}); if(found==widgets_.end()){lastError_=UiError::InvalidWidget;return false;} const bool hasChild=std::any_of(widgets_.begin(),widgets_.end(),[id](const Widget& widget){return widget.spec.parentId==id;}); if(hasChild){lastError_=UiError::MissingParent;return false;} if(capturedWidget_==id)capturedWidget_=0;if(focusedWidget_==id)focusedWidget_=0;widgets_.erase(found);lastError_=UiError::None;return true; }
uint16_t UiInputRouter::HitTest(float x,float y) const { if(!std::isfinite(x)||!std::isfinite(y))return 0; const Widget* winner=nullptr; for(const Widget& widget:widgets_){const UiWidgetSpec& spec=widget.spec;if(!spec.visible||!spec.interactive||x<spec.rect.x||y<spec.rect.y||x>=spec.rect.x+spec.rect.width||y>=spec.rect.y+spec.rect.height)continue;if(!winner||spec.zOrder>winner->spec.zOrder||(spec.zOrder==winner->spec.zOrder&&widget.sequence>winner->sequence))winner=&widget;}return winner?winner->spec.id:0; }
UiPointerResult UiInputRouter::RoutePointer(float x,float y,UiPointerPhase phase) { uint16_t target=capturedWidget_!=0U?capturedWidget_:HitTest(x,y); if(phase==UiPointerPhase::Press){capturedWidget_=target;if(IsFocusable(target))focusedWidget_=target;} const UiPointerResult result{target,capturedWidget_!=0U,target!=0U}; if(phase==UiPointerPhase::Release)capturedWidget_=0; lastError_=UiError::None;return result; }
bool UiInputRouter::SetFocus(uint16_t id){if(id==0U){focusedWidget_=0;lastError_=UiError::None;return true;}if(!IsFocusable(id)){lastError_=UiError::FocusUnavailable;return false;}focusedWidget_=id;lastError_=UiError::None;return true;}
UiKeyboardResult UiInputRouter::RouteKeyboard(UiKeyboardKey key){
    if(key==UiKeyboardKey::ClearFocus){const bool consumed=focusedWidget_!=0U;focusedWidget_=0;lastError_=UiError::None;return {0U,consumed,false};}
    if(key==UiKeyboardKey::Activate){if(!IsFocusable(focusedWidget_)){focusedWidget_=0;lastError_=UiError::None;return {};}lastError_=UiError::None;return {focusedWidget_,true,true};}
    if(key!=UiKeyboardKey::TabForward&&key!=UiKeyboardKey::TabBackward){lastError_=UiError::InvalidKey;return {};}
    std::vector<const Widget*> focusable;focusable.reserve(widgets_.size());for(const Widget& widget:widgets_)if(widget.spec.visible&&widget.spec.interactive&&widget.spec.focusable)focusable.push_back(&widget);std::sort(focusable.begin(),focusable.end(),[](const Widget* left,const Widget* right){return left->sequence<right->sequence;});
    if(focusable.empty()){focusedWidget_=0;lastError_=UiError::None;return {};}
    const bool forward=key==UiKeyboardKey::TabForward;size_t targetIndex=forward?0U:focusable.size()-1U;const auto current=std::find_if(focusable.begin(),focusable.end(),[this](const Widget* widget){return widget->spec.id==focusedWidget_;});if(current!=focusable.end()){const size_t index=static_cast<size_t>(current-focusable.begin());targetIndex=forward?(index+1U)%focusable.size():(index+focusable.size()-1U)%focusable.size();}
    focusedWidget_=focusable[targetIndex]->spec.id;lastError_=UiError::None;return {focusedWidget_,true,false};
}
std::vector<UiWidgetSpec> UiInputRouter::RenderableWidgets() const { std::vector<Widget> ordered; ordered.reserve(widgets_.size()); for(const Widget& widget:widgets_) if(widget.spec.visible) ordered.push_back(widget); std::stable_sort(ordered.begin(),ordered.end(),[](const Widget& left,const Widget& right){return left.spec.zOrder!=right.spec.zOrder?left.spec.zOrder<right.spec.zOrder:left.sequence<right.sequence;}); std::vector<UiWidgetSpec> result; result.reserve(ordered.size()); for(const Widget& widget:ordered) result.push_back(widget.spec); return result; }
} // namespace NeoEngine
