#include "OpenCodeIntegration.h"
#include <curl/curl.h>
#include <json/json.h>
#include <android/log.h>
#include <algorithm>
#include <cmath>

#define LOG_TAG "OpenCodeIntegration"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

namespace NeoEngine {

static size_t WriteCallback(void* contents, size_t size, size_t nmemb, std::string* output) {
    size_t totalSize = size * nmemb;
    if (output == nullptr || contents == nullptr || totalSize > 4U * 1024U * 1024U || output->size() > 4U * 1024U * 1024U - totalSize) return 0;
    output->append(static_cast<char*>(contents), totalSize);
    return totalSize;
}

OpenCodeIntegration::OpenCodeIntegration() : ready(false), generatorHandle(nullptr) {}
OpenCodeIntegration::~OpenCodeIntegration() { Shutdown(); }

bool OpenCodeIntegration::Initialize() {
    if (ready) return true;
    CURL* curl = curl_easy_init();
    if (!curl) { ready = false; return false; }
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:5000/health");
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 2L);
    CURLcode res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
    ready = (res == CURLE_OK);
    LOGI("OpenCode integration %s", ready ? "connected to Ruflo" : "unavailable");
    return ready;
}

void OpenCodeIntegration::Shutdown() { ready = false; }

GeneratedCode OpenCodeIntegration::GenerateFromDescription(const std::string& desc) {
    GeneratedCode gc;
    if (desc.empty() || desc.size() > 64U * 1024U || desc.find('\0') != std::string::npos) return gc;
    if (!ready) {
        // Fallback: generate template code locally
        gc.language = "cpp";
        gc.code = "// Generated by NeoEngine OpenCode for: " + desc + "\n"
                  "void GeneratedFeature() {\n"
                  "    // TODO: AI-powered implementation\n"
                  "}\n";
        gc.description = desc;
        gc.complexity = 3;
        return gc;
    }
    CURL* curl = curl_easy_init();
    if (!curl) return gc;
    Json::Value body;
    body["prompt"] = "Generate C++ game engine code for: " + desc;
    body["max_tokens"] = 2048;
    Json::FastWriter writer;
    std::string jsonBody = writer.write(body);
    std::string responseStr;
    struct curl_slist* headers = nullptr;
    headers = curl_slist_append(headers, "Content-Type: application/json");
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:8765/v1/chat/completions");
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, jsonBody.c_str());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &responseStr);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 60L);
    CURLcode res = curl_easy_perform(curl);
    curl_slist_free_all(headers);
    curl_easy_cleanup(curl);
    gc.language = "cpp";
    gc.code = res == CURLE_OK ? responseStr : "";
    if (gc.code.size() > 4U * 1024U * 1024U || gc.code.find('\0') != std::string::npos) gc.code.clear();
    gc.description = desc;
    gc.complexity = 5;
    return gc;
}

GeneratedCode OpenCodeIntegration::GenerateFromTemplate(const std::string& tmpl,
                                                        const std::map<std::string, std::string>& params) {
    GeneratedCode gc;
    gc.language = "cpp";
    gc.code = "// Template: " + tmpl + "\n";
    for (const auto& [k, v] : params) {
        gc.code += "// " + k + " = " + v + "\n";
    }
    gc.description = "From template " + tmpl;
    gc.complexity = 2;
    return gc;
}

std::vector<std::string> OpenCodeIntegration::GetSupportedLanguages() const {
    return {"cpp", "python", "javascript", "typescript", "java", "csharp"};
}

bool OpenCodeIntegration::ValidateCode(const GeneratedCode& code) {
    if (code.language.empty() || code.language.size() > 32U || code.code.empty() || code.code.size() > 4U * 1024U * 1024U) return false;
    if (code.code.find('\0') != std::string::npos || code.description.size() > 64U * 1024U) return false;
    return code.code.length() > 10;
}

bool OpenCodeIntegration::IsReady() const { return ready; }

} // namespace NeoEngine
