#include "Runtime/AnimationStateMachine.h"

#include <cmath>
#include <cstdio>
#include <limits>

int main() {
    using namespace NeoEngine;
    AnimationTimeline timeline; if(!timeline.AddTrack("idle",{{0,0},{1,0}})||!timeline.AddTrack("walk",{{0,10},{1,20}})||!timeline.AddEventMarker("idle",{"idle_transition_notify",0.2F})||!timeline.AddEventMarker("walk",{"walk_transition_notify",0.1F}))return 1;
    const float extreme = std::numeric_limits<float>::max();
    AnimationTimeline extremeTimeline; AnimationStateMachine extremeMachine; float extremeValue = 77.0F;
    if(!extremeTimeline.AddTrack("base-extreme",{{0.0F,-extreme},{1.0F,-extreme}})||!extremeTimeline.AddTrack("overlay-extreme",{{0.0F,extreme},{1.0F,extreme}})||!extremeMachine.AddState({"base-extreme","base-extreme",AnimationPlayback::Clamp})||!extremeMachine.AddState({"overlay-extreme","overlay-extreme",AnimationPlayback::Clamp})||!extremeMachine.AddTransition({"extreme-transition","base-extreme","overlay-extreme",1.0F})||!extremeMachine.Start("base-extreme")||!extremeMachine.Trigger("extreme-transition")||!extremeMachine.Update(0.5F)||!extremeMachine.Sample(extremeTimeline,extremeValue)||!std::isfinite(extremeValue)||std::abs(extremeValue)>1.0F)return 1;
    AnimationStateMachine machine; AnimationStateMachineSnapshot snapshot{}; float value=0; if(machine.AddState({"","idle"})||machine.LastError()!=AnimationStateMachineError::InvalidState||machine.AddState({std::string("nul\0state", 9U),"idle",AnimationPlayback::Loop})||machine.LastError()!=AnimationStateMachineError::InvalidState||machine.AddState({"invalid-playback","idle",static_cast<AnimationPlayback>(255U)})||machine.LastError()!=AnimationStateMachineError::InvalidState||!machine.AddState({"idle","idle",AnimationPlayback::Loop})||!machine.AddState({"walk","walk",AnimationPlayback::Loop})||machine.AddState({"walk","walk"})||machine.LastError()!=AnimationStateMachineError::DuplicateState)return 1;
    if(!machine.AddTransition({"idle_to_walk","idle","walk",0.5F})||!machine.AddTransition({"walk_to_idle","walk","idle",0.0F})||machine.AddTransition({std::string("nul\0transition", 14U),"idle","walk",0.5F})||machine.LastError()!=AnimationStateMachineError::InvalidTransition||machine.AddTransition({"too-long","idle","walk",AnimationStateMachine::kMaxTransitionDurationSeconds + 0.1F})||machine.LastError()!=AnimationStateMachineError::InvalidTransition||machine.AddTransition({"idle_to_walk","idle","walk",0.5F})||machine.LastError()!=AnimationStateMachineError::DuplicateTransition||machine.Trigger("idle_to_walk")||machine.LastError()!=AnimationStateMachineError::NotStarted||machine.Start(std::string("idle\0state", 10U))||machine.LastError()!=AnimationStateMachineError::InvalidState)return 1;
    if(!machine.Start("idle")||!machine.Snapshot(snapshot)||snapshot.activeStateId!="idle"||snapshot.blending||snapshot.activeTimeSeconds!=0.0F||!machine.Update(0.25F)||!machine.Sample(timeline,value)||std::fabs(value)>0.0001F||!machine.Trigger("idle_to_walk")||!machine.IsBlending()||!machine.Snapshot(snapshot)||snapshot.targetStateId!="walk"||snapshot.transitionId!="idle_to_walk"||!snapshot.blending||std::fabs(snapshot.activeTimeSeconds-0.25F)>0.0001F||snapshot.targetTimeSeconds!=0.0F||snapshot.blendFraction!=0.0F||!machine.Sample(timeline,value)||std::fabs(value)>0.0001F)return 1;
    if(!machine.Update(0.25F)||!machine.Snapshot(snapshot)||snapshot.transitionId!="idle_to_walk"||std::fabs(snapshot.blendFraction-0.5F)>0.0001F||std::fabs(snapshot.targetTimeSeconds-0.25F)>0.0001F||!machine.Sample(timeline,value)||std::fabs(value-6.25F)>0.0001F||!([&] { AnimationStateMachineSnapshot invalid = snapshot; invalid.transitionId = "walk_to_idle"; return !machine.Restore(invalid) && machine.LastError() == AnimationStateMachineError::InvalidSnapshot && machine.Restore(snapshot); })()||!([&] { AnimationStateMachineSnapshot invalid = snapshot; invalid.activeStateId = std::string("idle\0state", 10U); return !machine.Restore(invalid) && machine.LastError() == AnimationStateMachineError::InvalidSnapshot && machine.Snapshot(snapshot); })()||!([&] { return !machine.Trigger(std::string("idle\0transition", 15U)) && machine.LastError() == AnimationStateMachineError::InvalidTransition && machine.IsBlending(); })()||machine.Trigger("idle_to_walk")||machine.LastError()!=AnimationStateMachineError::TransitionInProgress)return 1;
    std::vector<std::string> transitionEvents;
    if(!machine.CollectEvents(timeline,0.0F,0.25F,transitionEvents)||transitionEvents.size()!=2U||transitionEvents[0]!="idle_transition_notify"||transitionEvents[1]!="walk_transition_notify")return 1;
    transitionEvents={"preserved"};
    if(machine.CollectEvents(timeline,0.5F,0.25F,transitionEvents)||machine.LastError()!=AnimationStateMachineError::EventCollectionFailed||transitionEvents.size()!=1U||transitionEvents[0]!="preserved")return 1;
    if(!machine.Update(0.25F)||machine.IsBlending()||machine.ActiveStateId()!="walk"||!machine.Snapshot(snapshot)||snapshot.blending||!snapshot.targetStateId.empty()||std::fabs(snapshot.activeTimeSeconds-0.5F)>0.0001F||!machine.Sample(timeline,value)||std::fabs(value-15.0F)>0.0001F||machine.Update(-0.1F)||machine.LastError()!=AnimationStateMachineError::InvalidDelta||!machine.Sample(timeline,value)||std::fabs(value-15.0F)>0.0001F||machine.Update(1.1F)||machine.LastError()!=AnimationStateMachineError::InvalidDelta||!machine.Sample(timeline,value)||std::fabs(value-15.0F)>0.0001F)return 1;
    AnimationStateMachineSnapshot residualTargetTime = snapshot;
    residualTargetTime.targetTimeSeconds = 1.0F;
    if(machine.Restore(residualTargetTime)||machine.LastError()!=AnimationStateMachineError::InvalidSnapshot||machine.ActiveStateId()!="walk"||machine.IsBlending())return 1;
    if(!machine.Trigger("walk_to_idle")||machine.ActiveStateId()!="idle"||machine.IsBlending()||!machine.Sample(timeline,value)||std::fabs(value)>0.0001F)return 1;
    AnimationStateMachine missing; if(!missing.AddState({"missing","not-present"})||missing.Snapshot(snapshot)||missing.LastError()!=AnimationStateMachineError::NotStarted||!missing.Start("missing")||missing.Sample(timeline,value)||missing.LastError()!=AnimationStateMachineError::SampleFailed)return 1;
    std::printf("ANIMATION_STATE_MACHINE_SMOKE_OK states=2 blend=1 snapshot=1 immediate=1 invalid=1 value=%.2f\n",value); return 0;
}
