#include "Runtime/AssetRefreshExecutor.h"

#include "Runtime/SoftwareRenderer.h"

#include <cstdio>
#include <string>
#include <vector>

int main() {
    using namespace NeoEngine;
    const auto bytes=[](const std::string& value){return std::vector<uint8_t>(value.begin(),value.end());};
    const std::string obj="v -1 -1 0\nv 1 -1 0\nv 0 1 0\nvn 0 0 -1\nf 1//1 2//1 3//1\n";
    const std::vector<uint8_t> redPpm{'P','6','\n','1',' ','1','\n','2','5','5','\n',255U,0U,0U};
    const std::vector<uint8_t> bluePpm{'P','6','\n','1',' ','1','\n','2','5','5','\n',0U,0U,255U};
    const std::vector<uint8_t> greenPpm{'P','6','\n','1',' ','1','\n','2','5','5','\n',0U,255U,0U};
    const std::vector<uint8_t> widePpm{'P','6','\n','2',' ','1','\n','2','5','5','\n',255U,0U,0U,0U,255U,0U};
    AssetRegistry registry;
    if(!registry.ImportBytes("mesh",AssetKind::Mesh,{},bytes(obj))||!registry.MarkReady("mesh")||!registry.ImportBytes("tile",AssetKind::Texture,{},redPpm)||!registry.MarkReady("tile"))return 1;
    TextureStagingStore textures;MeshStagingStore meshes;MaterialStagingStore materials;
    if(!textures.StagePpm(registry,"tile")||!meshes.StageObj(registry,"mesh"))return 1;
    const CpuMeshResource* mesh=meshes.Find("mesh");const CpuTextureResource* texture=textures.Find("tile");
    SceneWorld world;SceneEntity entity{};if(mesh==nullptr||texture==nullptr||!world.Create(entity)||!world.SetTransform(entity,{0,0,5,0,0,0,1,1,1})||!world.UpdateTransforms())return 1;
    MeshMaterial textureMaterial{0xFFFFFFFFU,0.2F,0.8F,texture};SceneMeshAdapter scene;if(!scene.AddStaged(entity,*mesh,textureMaterial))return 1;
    RenderCamera camera;if(!camera.Initialize({RenderCameraMode::Perspective,{0,0,0},5,90,1,0.1F,20}))return 1;
    auto pixel=[&](uint32_t& value){SoftwareRenderer renderer;if(!renderer.Initialize(64,64)||!renderer.Clear(0xFF000000U)||!scene.Draw(world,camera,renderer,{{0,0,-1}}))return false;value=renderer.PixelAt(32,32);return true;};uint32_t redPixel=0U;if(!pixel(redPixel)||redPixel!=0xFFFF0000U)return 1;
    AssetRefreshDiagnostics diagnostics;AssetRefreshExecutor executor;
    const uint64_t redHash=texture->sourceHash;if(!registry.ReplaceBytes("tile",bluePpm)||!diagnostics.BuildPlan(registry,"tile",textures,meshes,materials,scene)||diagnostics.Entries().size()!=2U||diagnostics.Entries()[0].action!=AssetRefreshAction::RefreshTexture||diagnostics.Entries()[1].action!=AssetRefreshAction::RebindSceneInstance||!executor.Preflight(diagnostics.Entries(),registry,textures,meshes,materials,scene)||executor.PreflightReceipts().size()!=2U||!executor.PreflightReceipts()[0].structurallyValid||!executor.PreflightReceipts()[1].structurallyValid||texture->sourceHash!=redHash||!executor.Execute(diagnostics.Entries(),registry,textures,meshes,materials,scene)||executor.LastError()!=AssetRefreshExecutorError::None||executor.Receipts().size()!=2U||!executor.Receipts()[0].succeeded||!executor.Receipts()[1].succeeded||!textures.IsCurrent(registry,"tile"))return 1;
    uint32_t bluePixel=0U;if(!pixel(bluePixel)||bluePixel!=0xFF0000FFU)return 1;
    SceneEntity spriteA{},spriteB{};SceneSpriteAdapter sprites;if(!world.Create(spriteA)||!world.Create(spriteB)||!sprites.AddStaged(spriteA,*textures.Find("tile"),1,1,0,0,0xFFFFFFFFU)||!sprites.AddStaged(spriteB,*textures.Find("tile"),1,1,0,1,0xFFFFFFFFU))return 1;
    const std::vector<SceneSpriteBindingSnapshot> initialSnapshots=sprites.BindingSnapshots();if(initialSnapshots.size()!=2U||initialSnapshots[0].entity!=spriteA||initialSnapshots[1].entity!=spriteB||initialSnapshots[0].sourceAssetId!="tile"||initialSnapshots[0].sourceHash!=registry.Find("tile")->contentHash)return 1;
    if(!registry.ReplaceBytes("tile",greenPpm)||!diagnostics.BuildPlan(registry,"tile",textures,meshes,materials,scene)||diagnostics.Entries().size()!=2U||diagnostics.Entries()[0].action!=AssetRefreshAction::RefreshTexture||diagnostics.Entries()[1].action!=AssetRefreshAction::RebindSceneInstance)return 1;
    SceneMeshAdapter emptyScene;AssetRefreshDiagnostics spriteDiagnostics;if(!spriteDiagnostics.BuildPlan(registry,"tile",textures,meshes,materials,emptyScene,sprites)||spriteDiagnostics.Entries().size()!=3U||spriteDiagnostics.Entries()[0].action!=AssetRefreshAction::RefreshTexture||spriteDiagnostics.Entries()[1].action!=AssetRefreshAction::RefreshSpriteInstance||spriteDiagnostics.Entries()[1].entity!=spriteA||spriteDiagnostics.Entries()[2].action!=AssetRefreshAction::RefreshSpriteInstance||spriteDiagnostics.Entries()[2].entity!=spriteB)return 1;
    const uint64_t greenHash=registry.Find("tile")->contentHash;if(!executor.ExecuteSpritesAtomic(spriteDiagnostics.Entries(),registry,textures,sprites)||!textures.IsCurrent(registry,"tile")||executor.PreflightReceipts().size()!=3U||executor.Receipts().size()!=3U||!executor.PreflightReceipts()[2].structurallyValid||!executor.Receipts()[2].succeeded)return 1;
    std::string spriteId;uint64_t boundA=0U,boundB=0U;if(!sprites.InspectStagedTexture(spriteA,spriteId,boundA)||spriteId!="tile"||boundA!=greenHash||!sprites.InspectStagedTexture(spriteB,spriteId,boundB)||boundB!=greenHash)return 1;
    uint32_t retainedBlue=0U;if(!pixel(retainedBlue)||retainedBlue!=bluePixel)return 1;
    if(!registry.ReplaceBytes("tile",redPpm)||!diagnostics.BuildPlan(registry,"tile",textures,meshes,materials,scene,sprites)||diagnostics.Entries().size()!=4U||diagnostics.Entries()[0].action!=AssetRefreshAction::RefreshTexture||diagnostics.Entries()[1].action!=AssetRefreshAction::RebindSceneInstance||diagnostics.Entries()[2].action!=AssetRefreshAction::RefreshSpriteInstance||diagnostics.Entries()[3].action!=AssetRefreshAction::RefreshSpriteInstance||!executor.ExecuteCombinedAtomic(diagnostics.Entries(),registry,textures,meshes,materials,scene,sprites)||executor.PreflightReceipts().size()!=4U||executor.Receipts().size()!=4U||!textures.IsCurrent(registry,"tile"))return 1;uint32_t restoredRed=0U;if(!pixel(restoredRed)||restoredRed!=redPixel)return 1;const uint64_t combinedHash=registry.Find("tile")->contentHash;if(!sprites.InspectStagedTexture(spriteA,spriteId,boundA)||boundA!=combinedHash||!sprites.InspectStagedTexture(spriteB,spriteId,boundB)||boundB!=combinedHash||scene.Instances().front().sourceTextureHash!=combinedHash)return 1;
    AssetRegistry rollbackRegistry;if(!rollbackRegistry.ImportBytes("mesh",AssetKind::Mesh,{},bytes(obj))||!rollbackRegistry.MarkReady("mesh")||!rollbackRegistry.ImportBytes("wide",AssetKind::Texture,{},widePpm)||!rollbackRegistry.MarkReady("wide"))return 1;TextureStagingStore rollbackTextures;MeshStagingStore rollbackMeshes;if(!rollbackTextures.StagePpm(rollbackRegistry,"wide")||!rollbackMeshes.StageObj(rollbackRegistry,"mesh"))return 1;SceneWorld rollbackWorld;SceneEntity rollbackA{},rollbackB{};SceneSpriteAdapter rollbackSprites;if(!rollbackWorld.Create(rollbackA)||!rollbackWorld.Create(rollbackB)||!rollbackSprites.AddStaged(rollbackA,*rollbackTextures.Find("wide"),1,1,0,0,0xFFFFFFFFU)||!rollbackSprites.AddStaged(rollbackB,*rollbackTextures.Find("wide"),1,1,0,1,0xFFFFFFFFU,0.0F,false,true,1U,0U,1U,1U))return 1;
    SceneEntity rollbackMeshEntity{};SceneMeshAdapter rollbackScene;if(!rollbackWorld.Create(rollbackMeshEntity)||!rollbackScene.AddStaged(rollbackMeshEntity,*rollbackMeshes.Find("mesh"),MeshMaterial{0xFFFFFFFFU,0.2F,0.8F,rollbackTextures.Find("wide")}))return 1;
    const uint64_t wideHash=rollbackTextures.Find("wide")->sourceHash;if(!rollbackRegistry.ReplaceBytes("wide",bluePpm))return 1;AssetRefreshDiagnostics rollbackDiagnostics;if(!rollbackDiagnostics.BuildPlan(rollbackRegistry,"wide",rollbackTextures,rollbackMeshes,materials,rollbackScene,rollbackSprites)||rollbackDiagnostics.Entries().size()!=4U||rollbackDiagnostics.Entries()[1].action!=AssetRefreshAction::RebindSceneInstance)return 1;const std::vector<AssetRefreshReceipt> retainedReceipts=executor.Receipts();const std::vector<AssetRefreshPreflightReceipt> retainedPreflight=executor.PreflightReceipts();if(executor.ExecuteCombinedAtomic(rollbackDiagnostics.Entries(),rollbackRegistry,rollbackTextures,rollbackMeshes,materials,rollbackScene,rollbackSprites)||executor.LastError()!=AssetRefreshExecutorError::ActionFailed||rollbackTextures.Find("wide")->sourceHash!=wideHash||rollbackTextures.IsCurrent(rollbackRegistry,"wide")||rollbackScene.Instances().front().sourceTextureHash!=wideHash||executor.Receipts().size()!=retainedReceipts.size()||executor.PreflightReceipts().size()!=retainedPreflight.size())return 1;uint64_t rollbackHashA=0U,rollbackHashB=0U;if(!rollbackSprites.InspectStagedTexture(rollbackA,spriteId,rollbackHashA)||rollbackHashA!=wideHash||!rollbackSprites.InspectStagedTexture(rollbackB,spriteId,rollbackHashB)||rollbackHashB!=wideHash)return 1;
    std::printf("ASSET_REFRESH_EXECUTOR_SMOKE_OK meshPlanStable=1 spriteSnapshot=1 deterministicSpritePlan=1 multiSpriteAtomic=1 mixedPlanAtomic=1 laterRectRollback=1 receiptsPreserved=1 releaseScope=cpu\n");
    return 0;
}
