#include "Runtime/EditorSceneSession.h"
#include "Runtime/SoftwareRenderer.h"

#include <cstdio>
#include <vector>

int main() {
    using namespace NeoEngine;
    const std::vector<uint8_t> ppm{'P','6','\n','1',' ','1','\n','2','5','5','\n',90U,230U,140U}; AssetRegistry assets; if(!assets.ImportBytes("session.sprite",AssetKind::Texture,{},ppm)||!assets.MarkReady("session.sprite"))return 1;
    EditorSceneDocument document{EditorSceneDocument::kVersion,"editor-session",1,{{5,0,EditorSceneActorKind::Empty,{}},{10,5,EditorSceneActorKind::Sprite,{0,0,3,0,0,0,1,1,1},"session.sprite","","","",1,1,0,0,0xFFFFFFFFU}}}; EditorSceneSession session; if(!session.Open(document,assets)||session.LastError()!=EditorSceneSessionError::None)return 1;
    const auto hierarchy=session.HierarchySnapshot(); EditorSceneActor inspected{}; EditorSceneActor selectedSentinel{99U}; EditorSceneDocument saved{}; if(hierarchy.size()!=2U||hierarchy[0].id!=5U||hierarchy[1].id!=10U||!session.InspectActor(10,inspected)||inspected.assetId!="session.sprite"||session.InspectSelected(selectedSentinel)||session.LastError()!=EditorSceneSessionError::NoSelection||selectedSentinel.id!=99U||!session.SelectActor(10)||!session.HasSelection()||session.SelectedActorId()!=10U||!session.InspectSelected(inspected)||inspected.id!=10U||inspected.assetId!="session.sprite"||session.SelectActor(99)||session.LastError()!=EditorSceneSessionError::UnknownActor||session.SelectedActorId()!=10U||!session.Save(saved)||saved.sceneId!=document.sceneId)return 1;
    RenderCamera camera; SoftwareRenderer renderer; if(!camera.Initialize({RenderCameraMode::Perspective,{},5,90,1,0.1F,20})||!renderer.Initialize(64,64)||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.PixelAt(32,32)==0xFF000000U)return 1; const uint64_t hash=renderer.FrameHash();
    if(!session.UpdateTransform(10,{0.5F,0,3,0,0,0,1,1,1},assets)||!session.Save(saved)||saved.revision!=2U||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.FrameHash()==hash)return 1; const uint64_t movedHash=renderer.FrameHash();
    if(!session.ReparentActor(10,0,assets)||!session.Save(saved)||saved.revision!=3U||!session.InspectActor(10,inspected)||inspected.parentId!=0U)return 1;
    if(session.ReparentActor(10,10,assets)||session.LastError()!=EditorSceneSessionError::DocumentLoadFailed||!session.Save(saved)||saved.revision!=3U||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.FrameHash()!=movedHash)return 1;
    if(!session.AddActor({20,0,EditorSceneActorKind::Empty,{}},assets)||!session.Save(saved)||saved.revision!=4U||session.HierarchySnapshot().size()!=3U||!session.ReparentActor(10,20,assets)||!session.Save(saved)||saved.revision!=5U)return 1;
    if(session.DeleteActor(20,assets)||session.LastError()!=EditorSceneSessionError::ActorHasChildren||!session.Save(saved)||saved.revision!=5U||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.FrameHash()!=movedHash)return 1;
    if(!session.ReparentActor(10,0,assets)||!session.SelectActor(20)||!session.DeleteActor(20,assets)||session.HasSelection()||!session.Save(saved)||saved.revision!=7U||session.HierarchySnapshot().size()!=2U)return 1;
    if(session.AddActor({5,0,EditorSceneActorKind::Empty,{}},assets)||session.LastError()!=EditorSceneSessionError::DocumentLoadFailed||!session.Save(saved)||saved.revision!=7U||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.FrameHash()!=movedHash)return 1;
    if(session.UpdateTransform(10,{0,0,3,0,0,0,0,1,1},assets)||session.LastError()!=EditorSceneSessionError::DocumentLoadFailed||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.FrameHash()!=movedHash)return 1;
    if(!session.SelectActor(10))return 1; EditorSceneDocument invalid=document; invalid.revision=2; invalid.actors[1].assetId="missing.sprite"; if(session.Open(invalid,assets)||session.LastError()!=EditorSceneSessionError::DocumentLoadFailed||session.SelectedActorId()!=10U||!renderer.Clear(0xFF000000U)||!session.RenderViewport(camera,renderer,{{0,0,-1}})||renderer.FrameHash()!=movedHash)return 1;
    EditorSceneDocument reduced{EditorSceneDocument::kVersion,"reduced",1,{{5,0,EditorSceneActorKind::Empty,{}}}}; if(!session.Open(reduced,assets)||session.HasSelection())return 1;
    const std::string obj="v -0.75 -0.75 0\nv 0.75 -0.75 0\nv 0 0.75 0\nvn 0 0 -1\nf 1//1 2//1 3//1\n"; const std::string mtl="newmtl red\nKd 0.9 0.2 0.2\nd 1\n"; const std::vector<uint8_t> broken{'N','O'}; AssetRegistry mixedAssets; if(!mixedAssets.ImportBytes("mixed.mesh",AssetKind::Mesh,{},std::vector<uint8_t>(obj.begin(),obj.end()))||!mixedAssets.MarkReady("mixed.mesh")||!mixedAssets.ImportBytes("mixed.material",AssetKind::Material,{},std::vector<uint8_t>(mtl.begin(),mtl.end()))||!mixedAssets.MarkReady("mixed.material")||!mixedAssets.ImportBytes("mixed.sprite",AssetKind::Texture,{},ppm)||!mixedAssets.MarkReady("mixed.sprite")||!mixedAssets.ImportBytes("broken.sprite",AssetKind::Texture,{},broken)||!mixedAssets.MarkReady("broken.sprite"))return 1;
    EditorSceneDocument mixed{EditorSceneDocument::kVersion,"mixed-session",1,{{.id=1,.kind=EditorSceneActorKind::Mesh,.transform={-1,0,3,0,0,0,1,1,1},.assetId="mixed.mesh",.materialAssetId="mixed.material",.materialName="red"},{.id=2,.kind=EditorSceneActorKind::Sprite,.transform={1,0,3,0,0,0,1,1,1},.assetId="mixed.sprite",.spriteWidth=1.0F,.spriteHeight=1.0F,.spriteLayer=1,.spriteOrder=0,.spriteRgba=0xFFFFFFFFU}}}; EditorSceneSession mixedSession; SoftwareRenderer mixedRenderer; if(!mixedSession.Open(mixed,mixedAssets)||!mixedRenderer.Initialize(64,64)||!mixedRenderer.Clear(0xFF000000U)||!mixedSession.RenderViewport(camera,mixedRenderer,{{0,0,-1}})||mixedRenderer.FrameHash()==0U)return 1; const uint64_t mixedHash=mixedRenderer.FrameHash(); EditorSceneDocument mixedBroken=mixed; mixedBroken.revision=2; mixedBroken.actors[1].assetId="broken.sprite"; if(mixedSession.Open(mixedBroken,mixedAssets)||mixedSession.LastError()!=EditorSceneSessionError::SpriteBindFailed||!mixedRenderer.Clear(0xFF000000U)||!mixedSession.RenderViewport(camera,mixedRenderer,{{0,0,-1}})||mixedRenderer.FrameHash()!=mixedHash)return 1;
    std::printf("EDITOR_SCENE_SESSION_SMOKE_OK hierarchy=1 inspector=1 selectedInspector=1 selection=1 save=1 viewport=1 mixed=1 edit=1 reparent=1 addDelete=1 atomicOpen=1 hash=%llu\n",static_cast<unsigned long long>(movedHash)); return 0;
}
