#include "Runtime/MaterialImportPipeline.h"

#include <cstdio>

int main() {
    using namespace NeoEngine;
    AssetRegistry registry; MaterialStagingStore materials; MaterialImportPipeline pipeline; MaterialImportReceipt receipt{};
    const std::vector<uint8_t> valid{'n','e','w','m','t','l',' ','f','a','r','m','\n','K','d',' ','0','.','2',' ','0','.','4',' ','0','.','6','\n','d',' ','0','.','5','\n'};
    if (!pipeline.ImportMtl(registry, materials, "farm.material", {}, valid, "farm", receipt) || pipeline.LastError()!=MaterialImportPipelineError::None || receipt.assetId!="farm.material" || receipt.materialName!="farm" || receipt.contentHash==0U || materials.ResourceCount()!=1U) return 1;
    const AssetDefinition* definition=registry.Find("farm.material"); const CpuMaterialResource* resource=materials.Find("farm.material","farm");
    if (definition==nullptr || definition->kind!=AssetKind::Material || definition->state!=AssetState::Ready || resource==nullptr || resource->sourceHash!=receipt.contentHash || resource->material.rgba!=receipt.rgba) return 1;
    const size_t assetCount=registry.All().size(), materialCount=materials.ResourceCount(); const MaterialImportReceipt initial=receipt;
    const std::vector<uint8_t> replacement{'n','e','w','m','t','l',' ','f','a','r','m','\n','K','d',' ','0','.','8',' ','0','.','1',' ','0','.','2','\n','d',' ','0','.','7','5','\n'};
    if(!pipeline.RefreshMtl(registry,materials,"farm.material",replacement,"farm",receipt)||pipeline.LastError()!=MaterialImportPipelineError::None||receipt.contentHash==initial.contentHash||receipt.rgba==initial.rgba||!materials.IsCurrent(registry,"farm.material","farm"))return 1;
    const MaterialImportReceipt preserved=receipt; const CpuMaterialResource* refreshed=materials.Find("farm.material","farm"); if(refreshed==nullptr||refreshed->sourceHash!=receipt.contentHash)return 1;
    const std::vector<uint8_t> malformed{'n','e','w','m','t','l',' ','b','a','d','\n','K','d',' ','2',' ','0',' ','0','\n'};
    if (pipeline.ImportMtl(registry,materials,"bad.material",{},malformed,"bad",receipt) || pipeline.LastError()!=MaterialImportPipelineError::StageFailed || registry.All().size()!=assetCount || materials.ResourceCount()!=materialCount || receipt.assetId!=preserved.assetId || receipt.contentHash!=preserved.contentHash) return 1;
    if (pipeline.ImportMtl(registry,materials,"farm.material",{},valid,"farm",receipt) || pipeline.LastError()!=MaterialImportPipelineError::RegistryImportFailed || registry.All().size()!=assetCount || materials.ResourceCount()!=materialCount) return 1;
    if(pipeline.RefreshMtl(registry,materials,"farm.material",malformed,"farm",receipt)||pipeline.LastError()!=MaterialImportPipelineError::StageFailed||receipt.contentHash!=preserved.contentHash||!materials.IsCurrent(registry,"farm.material","farm"))return 1;
    if(pipeline.RefreshMtl(registry,materials,"missing.material",replacement,"farm",receipt)||pipeline.LastError()!=MaterialImportPipelineError::RegistryReplaceFailed||receipt.contentHash!=preserved.contentHash||!materials.IsCurrent(registry,"farm.material","farm"))return 1;
    if (pipeline.ImportMtl(registry,materials,"",{},valid,"farm",receipt) || pipeline.LastError()!=MaterialImportPipelineError::InvalidRequest || pipeline.ImportMtl(registry,materials,"empty.material",{},valid,"",receipt) || pipeline.LastError()!=MaterialImportPipelineError::InvalidRequest) return 1;
    const std::vector<uint8_t> setValid{'n','e','w','m','t','l',' ','b','a','r','k','\n','K','d',' ','0','.','2',' ','0','.','4',' ','0','.','1','\n','n','e','w','m','t','l',' ','l','e','a','f','\n','K','d',' ','0','.','1',' ','0','.','7',' ','0','.','2','\n'}; std::vector<MaterialImportReceipt> receipts;
    if(!pipeline.ImportMtlSet(registry,materials,"foliage.material",{},setValid,{"bark","leaf"},receipts)||receipts.size()!=2U||receipts[0].materialName!="bark"||receipts[1].materialName!="leaf"||materials.Find("foliage.material","bark")==nullptr||materials.Find("foliage.material","leaf")==nullptr)return 1;
    const size_t setAssets=registry.All().size(),setMaterials=materials.ResourceCount();const std::vector<MaterialImportReceipt> setPreserved=receipts;
    if(pipeline.ImportMtlSet(registry,materials,"duplicate.material",{},setValid,{"bark","bark"},receipts)||pipeline.LastError()!=MaterialImportPipelineError::InvalidRequest||registry.All().size()!=setAssets||materials.ResourceCount()!=setMaterials||receipts.size()!=setPreserved.size())return 1;
    if(pipeline.ImportMtlSet(registry,materials,"missing.material",{},setValid,{"bark","missing"},receipts)||pipeline.LastError()!=MaterialImportPipelineError::StageFailed||registry.All().size()!=setAssets||materials.ResourceCount()!=setMaterials||receipts[0].materialName!=setPreserved[0].materialName)return 1;
    const std::vector<uint8_t> setReplacement{'n','e','w','m','t','l',' ','b','a','r','k','\n','K','d',' ','0','.','7',' ','0','.','1',' ','0','.','3','\n','n','e','w','m','t','l',' ','l','e','a','f','\n','K','d',' ','0','.','3',' ','0','.','2',' ','0','.','8','\n'};
    if(!pipeline.RefreshMtlSet(registry,materials,"foliage.material",setReplacement,{"bark","leaf"},receipts)||pipeline.LastError()!=MaterialImportPipelineError::None||receipts.size()!=2U||receipts[0].contentHash==setPreserved[0].contentHash||!materials.IsCurrent(registry,"foliage.material","bark")||!materials.IsCurrent(registry,"foliage.material","leaf"))return 1;
    const std::vector<MaterialImportReceipt> refreshedSet=receipts; const std::vector<uint8_t> malformedSet{'n','e','w','m','t','l',' ','b','a','r','k','\n','K','d',' ','0','.','1',' ','0','.','2',' ','0','.','3','\n','n','e','w','m','t','l',' ','l','e','a','f','\n','K','d',' ','2',' ','0',' ','0','\n'};
    if(pipeline.RefreshMtlSet(registry,materials,"foliage.material",malformedSet,{"bark","leaf"},receipts)||pipeline.LastError()!=MaterialImportPipelineError::StageFailed||receipts.size()!=refreshedSet.size()||receipts[0].contentHash!=refreshedSet[0].contentHash||!materials.IsCurrent(registry,"foliage.material","bark")||!materials.IsCurrent(registry,"foliage.material","leaf"))return 1;
    std::vector<std::string> oversized(MaterialImportPipeline::kMaxMaterialSet+1U,"bark"); if(pipeline.RefreshMtlSet(registry,materials,"foliage.material",setReplacement,oversized,receipts)||pipeline.LastError()!=MaterialImportPipelineError::InvalidRequest||receipts.size()!=refreshedSet.size())return 1;
    std::printf("MATERIAL_IMPORT_PIPELINE_SMOKE_OK assets=%zu materials=%zu set=2 hash=%llu atomic=1\n", registry.All().size(), materials.ResourceCount(), static_cast<unsigned long long>(preserved.contentHash)); return 0;
}
