#include "CommodityEconomyLedger.h"

#include <algorithm>
#include <cctype>
#include <limits>

namespace NeoEngine {
namespace {
constexpr uint32_t kMagic=0x314C4345U;
bool ValidCommandId(std::string_view id){return !id.empty()&&id.size()<=64U&&std::all_of(id.begin(),id.end(),[](unsigned char c){return std::isalnum(c)||c=='-'||c=='_';});}
bool Multiply(int64_t left,uint16_t right,int64_t& out){if(left<=0||right==0U||left>std::numeric_limits<int64_t>::max()/static_cast<int64_t>(right))return false;out=left*static_cast<int64_t>(right);return true;}
uint64_t Hash(const std::vector<uint8_t>& bytes){uint64_t hash=1469598103934665603ULL;for(uint8_t byte:bytes){hash^=byte;hash*=1099511628211ULL;}return hash;}
void U16(std::vector<uint8_t>& out,uint16_t value){out.push_back(static_cast<uint8_t>(value));out.push_back(static_cast<uint8_t>(value>>8U));}
void U32(std::vector<uint8_t>& out,uint32_t value){for(uint8_t shift=0;shift<4;++shift)out.push_back(static_cast<uint8_t>(value>>(shift*8U)));}
void I64(std::vector<uint8_t>& out,int64_t value){const uint64_t raw=static_cast<uint64_t>(value);for(uint8_t shift=0;shift<8;++shift)out.push_back(static_cast<uint8_t>(raw>>(shift*8U)));}
bool ReadU16(const std::vector<uint8_t>& in,size_t& offset,uint16_t& value){if(offset+2U>in.size())return false;value=static_cast<uint16_t>(in[offset])|static_cast<uint16_t>(in[offset+1U])<<8U;offset+=2U;return true;}
bool ReadU32(const std::vector<uint8_t>& in,size_t& offset,uint32_t& value){if(offset+4U>in.size())return false;value=0;for(uint8_t shift=0;shift<4;++shift)value|=static_cast<uint32_t>(in[offset+shift])<<(shift*8U);offset+=4U;return true;}
bool ReadI64(const std::vector<uint8_t>& in,size_t& offset,int64_t& value){if(offset+8U>in.size())return false;uint64_t raw=0;for(uint8_t shift=0;shift<8;++shift)raw|=static_cast<uint64_t>(in[offset+shift])<<(shift*8U);offset+=8U;value=static_cast<int64_t>(raw);return true;}
bool ReadText(const std::vector<uint8_t>& in,size_t& offset,size_t length,std::string& value){if(length>in.size()-offset)return false;value.assign(reinterpret_cast<const char*>(in.data()+offset),length);offset+=length;return true;}
}
bool CommodityEconomyLedger::HasApplied(std::string_view commandId) const {return std::find(appliedCommandIds_.begin(),appliedCommandIds_.end(),commandId)!=appliedCommandIds_.end();}
uint16_t CommodityEconomyLedger::Quantity(std::string_view commodityId) const {const auto found=std::find_if(inventory_.begin(),inventory_.end(),[commodityId](const InventoryEntry& entry){return entry.commodityId==commodityId;});return found==inventory_.end()?0U:found->quantity;}
bool CommodityEconomyLedger::Apply(const CommodityCatalog& catalog,const CommodityEconomyCommand& command){if(!ValidCommandId(command.id)){lastError_=CommodityEconomyError::InvalidCommand;return false;}if(HasApplied(command.id)){lastError_=CommodityEconomyError::None;return true;}if(appliedCommandIds_.size()>=kMaxAppliedCommands){lastError_=CommodityEconomyError::Capacity;return false;}const CommodityDefinition* definition=catalog.Find(command.commodityId);if(!definition){lastError_=CommodityEconomyError::UnknownCommodity;return false;}if(command.quantity==0U){lastError_=CommodityEconomyError::InvalidQuantity;return false;}auto found=std::find_if(inventory_.begin(),inventory_.end(),[&command](const InventoryEntry& entry){return entry.commodityId==command.commodityId;});const uint16_t current=found==inventory_.end()?0U:found->quantity;int64_t value=0;if((command.kind==CommodityEconomyKind::HarvestGrant||command.kind==CommodityEconomyKind::CraftGrant||command.kind==CommodityEconomyKind::QuestGrant||command.kind==CommodityEconomyKind::ShopBuy)&&static_cast<uint32_t>(current)+command.quantity>definition->maxStack){lastError_=CommodityEconomyError::InventoryLimit;return false;}if(command.kind==CommodityEconomyKind::ShopSell&&current<command.quantity){lastError_=CommodityEconomyError::InsufficientInventory;return false;}if((command.kind==CommodityEconomyKind::ShopBuy||command.kind==CommodityEconomyKind::ShopSell)&&(!definition->tradable||!Multiply(definition->baseUnitPrice,command.quantity,value))){lastError_=definition->tradable?CommodityEconomyError::Overflow:CommodityEconomyError::InvalidCommand;return false;}if(command.kind==CommodityEconomyKind::ShopBuy&&coins_<value){lastError_=CommodityEconomyError::InsufficientCoins;return false;}if(command.kind==CommodityEconomyKind::ShopSell&&coins_>std::numeric_limits<int64_t>::max()-value){lastError_=CommodityEconomyError::Overflow;return false;}if(found==inventory_.end()){if(inventory_.size()>=kMaxInventoryEntries){lastError_=CommodityEconomyError::Capacity;return false;}inventory_.push_back({command.commodityId,0U});found=std::prev(inventory_.end());}if(command.kind==CommodityEconomyKind::ShopSell){found->quantity=static_cast<uint16_t>(found->quantity-command.quantity);coins_+=value;}else{found->quantity=static_cast<uint16_t>(found->quantity+command.quantity);if(command.kind==CommodityEconomyKind::ShopBuy)coins_-=value;}appliedCommandIds_.push_back(command.id);lastError_=CommodityEconomyError::None;return true;}
bool CommodityEconomyLedger::Serialize(std::vector<uint8_t>& out) const {std::vector<InventoryEntry> inventory=inventory_;std::vector<std::string> commands=appliedCommandIds_;std::sort(inventory.begin(),inventory.end(),[](const InventoryEntry&a,const InventoryEntry&b){return a.commodityId<b.commodityId;});std::sort(commands.begin(),commands.end());out.clear();U32(out,kMagic);out.push_back(kVersion);I64(out,coins_);out.push_back(static_cast<uint8_t>(inventory.size()));U16(out,static_cast<uint16_t>(commands.size()));for(const InventoryEntry& entry:inventory){out.push_back(static_cast<uint8_t>(entry.commodityId.size()));U16(out,entry.quantity);out.insert(out.end(),entry.commodityId.begin(),entry.commodityId.end());}for(const std::string& command:commands){out.push_back(static_cast<uint8_t>(command.size()));out.insert(out.end(),command.begin(),command.end());}I64(out,static_cast<int64_t>(Hash(out)));return true;}
bool CommodityEconomyLedger::Deserialize(const CommodityCatalog& catalog,const std::vector<uint8_t>& bytes){if(bytes.size()<24U){lastError_=CommodityEconomyError::Corrupt;return false;}size_t offset=0;uint32_t magic=0;if(!ReadU32(bytes,offset,magic)||magic!=kMagic){lastError_=CommodityEconomyError::Corrupt;return false;}if(offset>=bytes.size()||bytes[offset++]!=kVersion){lastError_=CommodityEconomyError::UnsupportedVersion;return false;}int64_t coins=0;if(!ReadI64(bytes,offset,coins)||coins<0||offset>=bytes.size()){lastError_=CommodityEconomyError::Corrupt;return false;}const uint8_t inventoryCount=bytes[offset++];uint16_t commandCount=0;if(inventoryCount>kMaxInventoryEntries||!ReadU16(bytes,offset,commandCount)||commandCount>kMaxAppliedCommands){lastError_=CommodityEconomyError::Capacity;return false;}std::vector<InventoryEntry> inventory;std::vector<std::string> commands;inventory.reserve(inventoryCount);commands.reserve(commandCount);for(uint8_t index=0;index<inventoryCount;++index){if(offset>=bytes.size()){lastError_=CommodityEconomyError::Corrupt;return false;}const uint8_t idLength=bytes[offset++];uint16_t quantity=0;std::string id;if(idLength==0U||idLength>48U||!ReadU16(bytes,offset,quantity)||!ReadText(bytes,offset,idLength,id)){lastError_=CommodityEconomyError::Corrupt;return false;}const CommodityDefinition* definition=catalog.Find(id);if(!definition){lastError_=CommodityEconomyError::UnknownCommodity;return false;}if(quantity>definition->maxStack||std::any_of(inventory.begin(),inventory.end(),[&id](const InventoryEntry& entry){return entry.commodityId==id;})){lastError_=CommodityEconomyError::Corrupt;return false;}inventory.push_back({std::move(id),quantity});}for(uint16_t index=0;index<commandCount;++index){if(offset>=bytes.size()){lastError_=CommodityEconomyError::Corrupt;return false;}const uint8_t length=bytes[offset++];std::string id;if(length==0U||length>64U||!ReadText(bytes,offset,length,id)||!ValidCommandId(id)||std::find(commands.begin(),commands.end(),id)!=commands.end()){lastError_=CommodityEconomyError::Corrupt;return false;}commands.push_back(std::move(id));}int64_t expected=0;if(!ReadI64(bytes,offset,expected)){lastError_=CommodityEconomyError::Corrupt;return false;}if(offset!=bytes.size()){lastError_=CommodityEconomyError::TrailingBytes;return false;}std::vector<uint8_t> content(bytes.begin(),bytes.end()-8);if(static_cast<uint64_t>(expected)!=Hash(content)){lastError_=CommodityEconomyError::ChecksumMismatch;return false;}coins_=coins;inventory_=std::move(inventory);appliedCommandIds_=std::move(commands);lastError_=CommodityEconomyError::None;return true;}
} // namespace NeoEngine
