#include "CommodityCatalog.h"

#include <algorithm>
#include <cctype>

namespace NeoEngine {
namespace {
constexpr uint32_t kMagic=0x31444D43U;
uint64_t Hash(const std::vector<uint8_t>& bytes){uint64_t hash=1469598103934665603ULL;for(uint8_t byte:bytes){hash^=byte;hash*=1099511628211ULL;}return hash;}
void U32(std::vector<uint8_t>& out,uint32_t value){for(uint8_t shift=0;shift<4;++shift)out.push_back(static_cast<uint8_t>(value>>(shift*8U)));}
void I64(std::vector<uint8_t>& out,int64_t value){const uint64_t raw=static_cast<uint64_t>(value);for(uint8_t shift=0;shift<8;++shift)out.push_back(static_cast<uint8_t>(raw>>(shift*8U)));}
bool ReadU32(const std::vector<uint8_t>& in,size_t& offset,uint32_t& value){if(offset+4U>in.size())return false;value=0;for(uint8_t shift=0;shift<4;++shift)value|=static_cast<uint32_t>(in[offset+shift])<<(shift*8U);offset+=4U;return true;}
bool ReadI64(const std::vector<uint8_t>& in,size_t& offset,int64_t& value){if(offset+8U>in.size())return false;uint64_t raw=0;for(uint8_t shift=0;shift<8;++shift)raw|=static_cast<uint64_t>(in[offset+shift])<<(shift*8U);offset+=8U;value=static_cast<int64_t>(raw);return true;}
bool ValidId(std::string_view id){return !id.empty()&&id.size()<=CommodityCatalog::kMaxIdBytes&&std::all_of(id.begin(),id.end(),[](unsigned char c){return std::isalnum(c)||c=='-'||c=='_';});}
bool Valid(const CommodityDefinition& definition){return ValidId(definition.id)&&definition.baseUnitPrice>0&&definition.baseUnitPrice<=1000000000LL&&definition.maxStack>0&&definition.maxStack<=10000&&static_cast<uint8_t>(definition.category)<=static_cast<uint8_t>(CommodityCategory::QuestGood);}
}
bool CommodityCatalog::Add(CommodityDefinition definition){if(!Valid(definition)){lastError_=ValidId(definition.id)?CommodityCatalogError::InvalidDefinition:CommodityCatalogError::InvalidId;return false;}if(Find(definition.id)){lastError_=CommodityCatalogError::DuplicateId;return false;}if(definitions_.size()>=kMaxCommodities){lastError_=CommodityCatalogError::Capacity;return false;}definitions_.push_back(std::move(definition));lastError_=CommodityCatalogError::None;return true;}
const CommodityDefinition* CommodityCatalog::Find(std::string_view id) const {const auto found=std::find_if(definitions_.begin(),definitions_.end(),[id](const CommodityDefinition& definition){return definition.id==id;});return found==definitions_.end()?nullptr:&*found;}
bool CommodityCatalog::Serialize(std::vector<uint8_t>& out) const {std::vector<CommodityDefinition> ordered=definitions_;std::sort(ordered.begin(),ordered.end(),[](const CommodityDefinition&a,const CommodityDefinition&b){return a.id<b.id;});out.clear();U32(out,kMagic);out.push_back(kVersion);out.push_back(static_cast<uint8_t>(ordered.size()));for(const CommodityDefinition& definition:ordered){out.push_back(static_cast<uint8_t>(definition.id.size()));out.push_back(static_cast<uint8_t>(definition.category));I64(out,definition.baseUnitPrice);out.push_back(static_cast<uint8_t>(definition.maxStack));out.push_back(static_cast<uint8_t>(definition.maxStack>>8U));out.push_back(definition.tradable?1U:0U);out.insert(out.end(),definition.id.begin(),definition.id.end());}const uint64_t checksum=Hash(out);for(uint8_t shift=0;shift<8;++shift)out.push_back(static_cast<uint8_t>(checksum>>(shift*8U)));return true;}
bool CommodityCatalog::Deserialize(const std::vector<uint8_t>& bytes){if(bytes.size()<14U){lastError_=CommodityCatalogError::Corrupt;return false;}size_t offset=0;uint32_t magic=0;if(!ReadU32(bytes,offset,magic)||magic!=kMagic){lastError_=CommodityCatalogError::Corrupt;return false;}if(offset>=bytes.size()||bytes[offset++]!=kVersion){lastError_=CommodityCatalogError::UnsupportedVersion;return false;}if(offset>=bytes.size()){lastError_=CommodityCatalogError::Corrupt;return false;}const uint8_t count=bytes[offset++];if(count>kMaxCommodities){lastError_=CommodityCatalogError::Capacity;return false;}std::vector<CommodityDefinition> parsed;parsed.reserve(count);for(uint8_t index=0;index<count;++index){if(offset+13U>bytes.size()){lastError_=CommodityCatalogError::Corrupt;return false;}const uint8_t idLength=bytes[offset++],category=bytes[offset++];int64_t price=0;if(idLength==0U||idLength>kMaxIdBytes||!ReadI64(bytes,offset,price)||offset+3U>bytes.size()){lastError_=CommodityCatalogError::Corrupt;return false;}const uint16_t maxStack=static_cast<uint16_t>(bytes[offset])|static_cast<uint16_t>(bytes[offset+1U])<<8U;const uint8_t tradable=bytes[offset+2U];offset+=3U;if(tradable>1U||offset+idLength>bytes.size()){lastError_=CommodityCatalogError::Corrupt;return false;}std::string id(reinterpret_cast<const char*>(bytes.data()+offset),idLength);offset+=idLength;CommodityDefinition definition{std::move(id),static_cast<CommodityCategory>(category),price,maxStack,tradable==1U};if(!Valid(definition)||std::any_of(parsed.begin(),parsed.end(),[&definition](const CommodityDefinition& other){return other.id==definition.id;})){lastError_=CommodityCatalogError::Corrupt;return false;}parsed.push_back(std::move(definition));}if(offset+8U!=bytes.size()){lastError_=offset+8U>bytes.size()?CommodityCatalogError::Corrupt:CommodityCatalogError::TrailingBytes;return false;}uint64_t expected=0;for(uint8_t shift=0;shift<8;++shift)expected|=static_cast<uint64_t>(bytes[offset+shift])<<(shift*8U);std::vector<uint8_t> content(bytes.begin(),bytes.begin()+static_cast<std::ptrdiff_t>(offset));if(Hash(content)!=expected){lastError_=CommodityCatalogError::ChecksumMismatch;return false;}definitions_=std::move(parsed);lastError_=CommodityCatalogError::None;return true;}
} // namespace NeoEngine
