#include "Runtime/VulkanGraphicsPipeline.h"
#include "Runtime/VulkanGPUBuffer.h"
#include "Renderer/GPUDrivenRenderer.h"
#include <vulkan/vulkan.h>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <limits>
#include <vector>

namespace {
constexpr uint32_t N=GPUDrivenRenderer::MaxCommands, W=64, H=64;
struct R { VkDevice d=VK_NULL_HANDLE; VkCommandPool pool=VK_NULL_HANDLE; VkCommandBuffer cb=VK_NULL_HANDLE; VkFence fence=VK_NULL_HANDLE; VkImage image=VK_NULL_HANDLE; VkDeviceMemory imageMem=VK_NULL_HANDLE; VkImageView view=VK_NULL_HANDLE; VkFramebuffer fb=VK_NULL_HANDLE; VkRenderPass rp=VK_NULL_HANDLE; VkBuffer readback=VK_NULL_HANDLE; VkDeviceMemory readbackMem=VK_NULL_HANDLE; ~R(){if(!d)return;vkDeviceWaitIdle(d);if(fence)vkDestroyFence(d,fence,nullptr);if(fb)vkDestroyFramebuffer(d,fb,nullptr);if(view)vkDestroyImageView(d,view,nullptr);if(rp)vkDestroyRenderPass(d,rp,nullptr);if(readback)vkDestroyBuffer(d,readback,nullptr);if(readbackMem)vkFreeMemory(d,readbackMem,nullptr);if(image)vkDestroyImage(d,image,nullptr);if(imageMem)vkFreeMemory(d,imageMem,nullptr);if(pool)vkDestroyCommandPool(d,pool,nullptr);}};
uint32_t MT(VkPhysicalDevice p,uint32_t bits,VkMemoryPropertyFlags f){VkPhysicalDeviceMemoryProperties m{};vkGetPhysicalDeviceMemoryProperties(p,&m);for(uint32_t i=0;i<m.memoryTypeCount;i++)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&f)==f)return i;return UINT32_MAX;}
std::vector<uint32_t> SPV(const char* p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)return{};auto n=f.tellg();if(n<=0||n%4)return{};std::vector<uint32_t>x((size_t)n/4);f.seekg(0);f.read((char*)x.data(),n);return x;}
struct V{float p[3],n[3],uv[2];}; struct I{float m[16];};
}
int main(){
 VkApplicationInfo ai{VK_STRUCTURE_TYPE_APPLICATION_INFO};ai.pApplicationName="FauzanEngine2 R3 10k GPU indirect execution";ai.apiVersion=VK_API_VERSION_1_0;VkInstanceCreateInfo ici{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ici.pApplicationInfo=&ai;VkInstance inst=VK_NULL_HANDLE;if(vkCreateInstance(&ici,nullptr,&inst)!=VK_SUCCESS)return 1;
 uint32_t pc=0;if(vkEnumeratePhysicalDevices(inst,&pc,nullptr)!=VK_SUCCESS||!pc)return 1;std::vector<VkPhysicalDevice> ps(pc);vkEnumeratePhysicalDevices(inst,&pc,ps.data());VkPhysicalDevice p=ps[0];VkPhysicalDeviceProperties prop{};vkGetPhysicalDeviceProperties(p,&prop);if(prop.limits.maxDrawIndirectCount<N){std::printf("R3_GPU_10K_SKIP maxDrawIndirectCount=%u\n",prop.limits.maxDrawIndirectCount);vkDestroyInstance(inst,nullptr);return 0;}
 uint32_t fc=0;vkGetPhysicalDeviceQueueFamilyProperties(p,&fc,nullptr);std::vector<VkQueueFamilyProperties> fp(fc);vkGetPhysicalDeviceQueueFamilyProperties(p,&fc,fp.data());uint32_t qf=UINT32_MAX;for(uint32_t i=0;i<fc;i++)if(fp[i].queueFlags&VK_QUEUE_GRAPHICS_BIT){qf=i;break;}if(qf==UINT32_MAX)return 1;
 float pr=1;VkDeviceQueueCreateInfo qci{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qci.queueFamilyIndex=qf;qci.queueCount=1;qci.pQueuePriorities=&pr;VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};dci.queueCreateInfoCount=1;dci.pQueueCreateInfos=&qci;VkDevice d=VK_NULL_HANDLE;if(vkCreateDevice(p,&dci,nullptr,&d)!=VK_SUCCESS)return 1;VkQueue q=VK_NULL_HANDLE;vkGetDeviceQueue(d,qf,0,&q);R r;r.d=d;
 VkCommandPoolCreateInfo pci{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};pci.queueFamilyIndex=qf;pci.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;if(vkCreateCommandPool(d,&pci,nullptr,&r.pool)!=VK_SUCCESS)return 1;VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};cai.commandPool=r.pool;cai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;cai.commandBufferCount=1;if(vkAllocateCommandBuffers(d,&cai,&r.cb)!=VK_SUCCESS)return 1;
 VkDeviceSize pixels=(VkDeviceSize)W*H*4;VkImageCreateInfo im{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};im.imageType=VK_IMAGE_TYPE_2D;im.format=VK_FORMAT_R8G8B8A8_UNORM;im.extent={W,H,1};im.mipLevels=1;im.arrayLayers=1;im.samples=VK_SAMPLE_COUNT_1_BIT;im.tiling=VK_IMAGE_TILING_OPTIMAL;im.usage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT;im.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(vkCreateImage(d,&im,nullptr,&r.image)!=VK_SUCCESS)return 1;VkMemoryRequirements mr{};vkGetImageMemoryRequirements(d,r.image,&mr);uint32_t mt=MT(p,mr.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(mt==UINT32_MAX)return 1;VkMemoryAllocateInfo ma{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ma.allocationSize=mr.size;ma.memoryTypeIndex=mt;if(vkAllocateMemory(d,&ma,nullptr,&r.imageMem)!=VK_SUCCESS||vkBindImageMemory(d,r.image,r.imageMem,0)!=VK_SUCCESS)return 1;
 VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=pixels;bi.usage=VK_BUFFER_USAGE_TRANSFER_DST_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(vkCreateBuffer(d,&bi,nullptr,&r.readback)!=VK_SUCCESS)return 1;vkGetBufferMemoryRequirements(d,r.readback,&mr);mt=MT(p,mr.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);if(mt==UINT32_MAX)return 1;ma.allocationSize=mr.size;ma.memoryTypeIndex=mt;if(vkAllocateMemory(d,&ma,nullptr,&r.readbackMem)!=VK_SUCCESS||vkBindBufferMemory(d,r.readback,r.readbackMem,0)!=VK_SUCCESS)return 1;
 VkAttachmentDescription ad{};ad.format=VK_FORMAT_R8G8B8A8_UNORM;ad.samples=VK_SAMPLE_COUNT_1_BIT;ad.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;ad.storeOp=VK_ATTACHMENT_STORE_OP_STORE;ad.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ad.finalLayout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;VkAttachmentReference ar{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};VkSubpassDescription sub{};sub.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sub.colorAttachmentCount=1;sub.pColorAttachments=&ar;VkSubpassDependency dep{};dep.srcSubpass=0;dep.dstSubpass=VK_SUBPASS_EXTERNAL;dep.srcStageMask=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;dep.srcAccessMask=VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;dep.dstStageMask=VK_PIPELINE_STAGE_TRANSFER_BIT;dep.dstAccessMask=VK_ACCESS_TRANSFER_READ_BIT;VkRenderPassCreateInfo rpc{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};rpc.attachmentCount=1;rpc.pAttachments=&ad;rpc.subpassCount=1;rpc.pSubpasses=&sub;rpc.dependencyCount=1;rpc.pDependencies=&dep;if(vkCreateRenderPass(d,&rpc,nullptr,&r.rp)!=VK_SUCCESS)return 1;VkImageViewCreateInfo iv{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};iv.image=r.image;iv.viewType=VK_IMAGE_VIEW_TYPE_2D;iv.format=VK_FORMAT_R8G8B8A8_UNORM;iv.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;iv.subresourceRange.levelCount=1;iv.subresourceRange.layerCount=1;if(vkCreateImageView(d,&iv,nullptr,&r.view)!=VK_SUCCESS)return 1;VkFramebufferCreateInfo fbi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fbi.renderPass=r.rp;fbi.attachmentCount=1;fbi.pAttachments=&r.view;fbi.width=W;fbi.height=H;fbi.layers=1;if(vkCreateFramebuffer(d,&fbi,nullptr,&r.fb)!=VK_SUCCESS)return 1;
 NeoEngine::VulkanGPUBuffer vb,ib;V verts[3]={{{-0.8f,-0.8f,0},{0,0,1},{0,0}},{{0.8f,-0.8f,0},{0,0,1},{1,0}},{{0,0.8f,0},{0,0,1},{0.5f,1}}};uint32_t idx[3]={0,1,2};if(!vb.Initialize(d,p,sizeof(verts),NeoEngine::VulkanBufferType::VertexBuffer,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)||!vb.UploadData(verts,sizeof(verts))||!ib.Initialize(d,p,sizeof(idx),NeoEngine::VulkanBufferType::IndexBuffer,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)||!ib.UploadData(idx,sizeof(idx)))return 1;
 I* instances=new I[N];for(uint32_t i=0;i<N;i++){for(float& x:instances[i].m)x=0;instances[i].m[0]=instances[i].m[5]=instances[i].m[10]=instances[i].m[15]=1;}NeoEngine::VulkanGPUBuffer instBuf;if(!instBuf.Initialize(d,p,sizeof(I)*N,NeoEngine::VulkanBufferType::VertexBuffer,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)||!instBuf.UploadData(instances,sizeof(I)*N)){delete[] instances;return 1;}delete[] instances;
 NeoEngine::VulkanPipelineConfig cfg{};cfg.renderPass=r.rp;cfg.vertexSpv=SPV(NEO_SHADER_DIR "/neo_mesh.vert.spv");cfg.fragmentSpv=SPV(NEO_SHADER_DIR "/neo_mesh.frag.spv");cfg.cullMode=VK_CULL_MODE_NONE;cfg.depthTestEnable=false;cfg.depthWriteEnable=false;cfg.vertexBinding={0,sizeof(V),VK_VERTEX_INPUT_RATE_VERTEX};cfg.vertexAttributes={{0,0,VK_FORMAT_R32G32B32_SFLOAT,0},{1,0,VK_FORMAT_R32G32B32_SFLOAT,12},{2,0,VK_FORMAT_R32G32_SFLOAT,24},{3,1,VK_FORMAT_R32G32B32A32_SFLOAT,0},{4,1,VK_FORMAT_R32G32B32A32_SFLOAT,16},{5,1,VK_FORMAT_R32G32B32A32_SFLOAT,32},{6,1,VK_FORMAT_R32G32B32A32_SFLOAT,48}};cfg.additionalVertexBindings={{1,sizeof(I),VK_VERTEX_INPUT_RATE_INSTANCE}};cfg.pushConstantRanges={{VK_SHADER_STAGE_VERTEX_BIT,0,sizeof(float)*16}};NeoEngine::VulkanGraphicsPipeline pipe;if(!pipe.Initialize(d,cfg))return 1;
 GPUDrivenRenderer gpu;if(!gpu.Initialize(d,p,N))return 1;for(uint32_t i=0;i<N;i++)if(!gpu.TrySubmitDraw({3,1,0,0,i}))return 1;if(gpu.PendingDrawCount()!=N)return 1;
 VkCommandBufferBeginInfo cbi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};if(vkBeginCommandBuffer(r.cb,&cbi)!=VK_SUCCESS)return 1;VkClearValue clear{};clear.color={{0,0,0,1}};VkRenderPassBeginInfo rbi{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};rbi.renderPass=r.rp;rbi.framebuffer=r.fb;rbi.renderArea.extent={W,H};rbi.clearValueCount=1;rbi.pClearValues=&clear;vkCmdBeginRenderPass(r.cb,&rbi,VK_SUBPASS_CONTENTS_INLINE);VkViewport vp{0,0,(float)W,(float)H,0,1};VkRect2D sc{{0,0},{W,H}};vkCmdSetViewport(r.cb,0,1,&vp);vkCmdSetScissor(r.cb,0,1,&sc);vkCmdBindPipeline(r.cb,VK_PIPELINE_BIND_POINT_GRAPHICS,pipe.GetPipeline());VkBuffer vbs[2]={vb.GetBuffer(),instBuf.GetBuffer()};VkDeviceSize offs[2]={0,0};vkCmdBindVertexBuffers(r.cb,0,2,vbs,offs);vkCmdBindIndexBuffer(r.cb,ib.GetBuffer(),0,VK_INDEX_TYPE_UINT32);float m[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};vkCmdPushConstants(r.cb,pipe.GetPipelineLayout(),VK_SHADER_STAGE_VERTEX_BIT,0,sizeof(m),m);if(!gpu.Execute(r.cb)||gpu.PendingDrawCount()!=0)return 1;vkCmdEndRenderPass(r.cb);VkBufferImageCopy copy{};copy.bufferRowLength=W;copy.bufferImageHeight=H;copy.imageSubresource.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;copy.imageSubresource.layerCount=1;copy.imageExtent={W,H,1};vkCmdCopyImageToBuffer(r.cb,r.image,VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,r.readback,1,&copy);if(vkEndCommandBuffer(r.cb)!=VK_SUCCESS)return 1;
 VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};if(vkCreateFence(d,&fi,nullptr,&r.fence)!=VK_SUCCESS)return 1;VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&r.cb;if(vkQueueSubmit(q,1,&si,r.fence)!=VK_SUCCESS||vkWaitForFences(d,1,&r.fence,VK_TRUE,std::numeric_limits<uint64_t>::max())!=VK_SUCCESS)return 1;void* mapped=nullptr;if(vkMapMemory(d,r.readbackMem,0,pixels,0,&mapped)!=VK_SUCCESS)return 1;uint32_t non=0;auto* px=(uint8_t*)mapped;for(VkDeviceSize i=0;i<pixels;i+=4)if(px[i]||px[i+1]||px[i+2])non++;vkUnmapMemory(d,r.readbackMem);if(!non)return 1;std::printf("R3_GPU_10K_OK draws=%u non_clear_pixels=%u\n",N,non);
 pipe.Destroy();instBuf.Destroy();ib.Destroy();vb.Destroy();gpu.Destroy();vkDestroyDevice(d,nullptr);r.d=VK_NULL_HANDLE;vkDestroyInstance(inst,nullptr);return 0;}
