#include "Runtime/VulkanGraphicsPipeline.h"
#include "Runtime/VulkanGPUBuffer.h"
#include "Runtime/VulkanMeshBatchBuffer.h"
#include "Renderer/GPUDrivenRenderer.h"

#include <vulkan/vulkan.h>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <limits>
#include <vector>

namespace {
constexpr VkFormat kColorFormat=VK_FORMAT_R8G8B8A8_UNORM; constexpr uint32_t kWidth=128,kHeight=128;
struct Resources { VkDevice device=VK_NULL_HANDLE; VkCommandPool pool=VK_NULL_HANDLE; VkCommandBuffer commandBuffer=VK_NULL_HANDLE; VkFence fence=VK_NULL_HANDLE; VkImage image=VK_NULL_HANDLE; VkDeviceMemory imageMemory=VK_NULL_HANDLE; VkImageView view=VK_NULL_HANDLE; VkFramebuffer framebuffer=VK_NULL_HANDLE; VkRenderPass renderPass=VK_NULL_HANDLE; VkBuffer readback=VK_NULL_HANDLE; VkDeviceMemory readbackMemory=VK_NULL_HANDLE;
~Resources(){if(!device)return;vkDeviceWaitIdle(device);if(fence)vkDestroyFence(device,fence,nullptr);if(framebuffer)vkDestroyFramebuffer(device,framebuffer,nullptr);if(view)vkDestroyImageView(device,view,nullptr);if(renderPass)vkDestroyRenderPass(device,renderPass,nullptr);if(readback)vkDestroyBuffer(device,readback,nullptr);if(readbackMemory)vkFreeMemory(device,readbackMemory,nullptr);if(image)vkDestroyImage(device,image,nullptr);if(imageMemory)vkFreeMemory(device,imageMemory,nullptr);if(pool)vkDestroyCommandPool(device,pool,nullptr);}};
uint32_t FindMemoryType(VkPhysicalDevice p,uint32_t bits,VkMemoryPropertyFlags flags){VkPhysicalDeviceMemoryProperties m{};vkGetPhysicalDeviceMemoryProperties(p,&m);for(uint32_t i=0;i<m.memoryTypeCount;++i)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&flags)==flags)return i;return UINT32_MAX;}
std::vector<uint32_t> ReadSpv(const char* path){std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f)return{};auto s=f.tellg();if(s<=0||s%static_cast<std::streamoff>(sizeof(uint32_t))!=0)return{};std::vector<uint32_t> c(static_cast<size_t>(s)/sizeof(uint32_t));f.seekg(0);f.read(reinterpret_cast<char*>(c.data()),s);return c;}
NeoEngine::MeshVertex3D Vertex(float x,float y){return{{x,y,0.0f},{0.0f,0.0f,1.0f},{0.0f,0.0f}};}
}
int main(){
VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="FauzanEngine2 R3 real GPU indirect batch smoke";app.apiVersion=VK_API_VERSION_1_0;VkInstanceCreateInfo ii{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ii.pApplicationInfo=&app;VkInstance instance=VK_NULL_HANDLE;if(vkCreateInstance(&ii,nullptr,&instance)!=VK_SUCCESS)return 1;
uint32_t pc=0;if(vkEnumeratePhysicalDevices(instance,&pc,nullptr)!=VK_SUCCESS||pc==0){vkDestroyInstance(instance,nullptr);return 1;}std::vector<VkPhysicalDevice> ps(pc);vkEnumeratePhysicalDevices(instance,&pc,ps.data());VkPhysicalDevice physical=ps.front();uint32_t fc=0;vkGetPhysicalDeviceQueueFamilyProperties(physical,&fc,nullptr);std::vector<VkQueueFamilyProperties> fs(fc);vkGetPhysicalDeviceQueueFamilyProperties(physical,&fc,fs.data());uint32_t gf=UINT32_MAX;for(uint32_t i=0;i<fc;++i)if(fs[i].queueFlags&VK_QUEUE_GRAPHICS_BIT){gf=i;break;}if(gf==UINT32_MAX){vkDestroyInstance(instance,nullptr);return 1;}
float priority=1.0f;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=gf;qi.queueCount=1;qi.pQueuePriorities=&priority;VkDeviceCreateInfo di{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};di.queueCreateInfoCount=1;di.pQueueCreateInfos=&qi;VkDevice device=VK_NULL_HANDLE;if(vkCreateDevice(physical,&di,nullptr,&device)!=VK_SUCCESS){vkDestroyInstance(instance,nullptr);return 1;}VkQueue queue=VK_NULL_HANDLE;vkGetDeviceQueue(device,gf,0,&queue);Resources r{};r.device=device;
VkCommandPoolCreateInfo cpi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};cpi.queueFamilyIndex=gf;cpi.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;if(vkCreateCommandPool(device,&cpi,nullptr,&r.pool)!=VK_SUCCESS)return 1;VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};cai.commandPool=r.pool;cai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;cai.commandBufferCount=1;if(vkAllocateCommandBuffers(device,&cai,&r.commandBuffer)!=VK_SUCCESS)return 1;
const VkDeviceSize bytes=static_cast<VkDeviceSize>(kWidth)*kHeight*4;VkImageCreateInfo im{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};im.imageType=VK_IMAGE_TYPE_2D;im.format=kColorFormat;im.extent={kWidth,kHeight,1};im.mipLevels=1;im.arrayLayers=1;im.samples=VK_SAMPLE_COUNT_1_BIT;im.tiling=VK_IMAGE_TILING_OPTIMAL;im.usage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT;im.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(vkCreateImage(device,&im,nullptr,&r.image)!=VK_SUCCESS)return 1;VkMemoryRequirements mr{};vkGetImageMemoryRequirements(device,r.image,&mr);uint32_t mt=FindMemoryType(physical,mr.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(mt==UINT32_MAX)return 1;VkMemoryAllocateInfo ma{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ma.allocationSize=mr.size;ma.memoryTypeIndex=mt;if(vkAllocateMemory(device,&ma,nullptr,&r.imageMemory)!=VK_SUCCESS||vkBindImageMemory(device,r.image,r.imageMemory,0)!=VK_SUCCESS)return 1;
VkBufferCreateInfo rb{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};rb.size=bytes;rb.usage=VK_BUFFER_USAGE_TRANSFER_DST_BIT;rb.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(vkCreateBuffer(device,&rb,nullptr,&r.readback)!=VK_SUCCESS)return 1;vkGetBufferMemoryRequirements(device,r.readback,&mr);mt=FindMemoryType(physical,mr.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);if(mt==UINT32_MAX)return 1;ma.allocationSize=mr.size;ma.memoryTypeIndex=mt;if(vkAllocateMemory(device,&ma,nullptr,&r.readbackMemory)!=VK_SUCCESS||vkBindBufferMemory(device,r.readback,r.readbackMemory,0)!=VK_SUCCESS)return 1;
VkAttachmentDescription ad{};ad.format=kColorFormat;ad.samples=VK_SAMPLE_COUNT_1_BIT;ad.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;ad.storeOp=VK_ATTACHMENT_STORE_OP_STORE;ad.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ad.finalLayout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;VkAttachmentReference ar{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};VkSubpassDescription sp{};sp.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sp.colorAttachmentCount=1;sp.pColorAttachments=&ar;VkSubpassDependency dep{};dep.srcSubpass=0;dep.dstSubpass=VK_SUBPASS_EXTERNAL;dep.srcStageMask=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;dep.srcAccessMask=VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;dep.dstStageMask=VK_PIPELINE_STAGE_TRANSFER_BIT;dep.dstAccessMask=VK_ACCESS_TRANSFER_READ_BIT;VkRenderPassCreateInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};rp.attachmentCount=1;rp.pAttachments=&ad;rp.subpassCount=1;rp.pSubpasses=&sp;rp.dependencyCount=1;rp.pDependencies=&dep;if(vkCreateRenderPass(device,&rp,nullptr,&r.renderPass)!=VK_SUCCESS)return 1;
VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=r.image;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=kColorFormat;vi.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;vi.subresourceRange.levelCount=1;vi.subresourceRange.layerCount=1;if(vkCreateImageView(device,&vi,nullptr,&r.view)!=VK_SUCCESS)return 1;VkFramebufferCreateInfo fi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fi.renderPass=r.renderPass;fi.attachmentCount=1;fi.pAttachments=&r.view;fi.width=kWidth;fi.height=kHeight;fi.layers=1;if(vkCreateFramebuffer(device,&fi,nullptr,&r.framebuffer)!=VK_SUCCESS)return 1;
NeoEngine::VulkanMeshBufferBuilder a,b;std::vector<NeoEngine::MeshVertex3D> va={Vertex(-0.95f,-0.75f),Vertex(-0.10f,-0.75f),Vertex(-0.52f,0.75f)},vb={Vertex(0.10f,-0.75f),Vertex(0.95f,-0.75f),Vertex(0.52f,0.75f)};std::vector<uint32_t> idx={0,1,2};if(!a.BuildMesh(device,physical,va,idx)||!b.BuildMesh(device,physical,vb,idx))return 1;NeoEngine::VulkanMeshBatchBuffer batch;std::vector<const NeoEngine::VulkanMeshBufferBuilder*> meshes={&a,&b};if(!batch.Build(device,physical,meshes)||batch.MeshCount()!=2)return 1;if(batch.GetRange(0).vertexOffset!=0||batch.GetRange(1).vertexOffset!=3||batch.GetRange(1).firstIndex!=3)return 1;
struct Instance{float model[16];} instances[2]{};for(auto& x:instances)x.model[0]=x.model[5]=x.model[10]=x.model[15]=1.0f;NeoEngine::VulkanGPUBuffer ib;if(!ib.Initialize(device,physical,sizeof(instances),NeoEngine::VulkanBufferType::VertexBuffer,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)||!ib.UploadData(instances,sizeof(instances)))return 1;
NeoEngine::VulkanPipelineConfig cfg{};cfg.renderPass=r.renderPass;cfg.vertexSpv=ReadSpv(NEO_SHADER_DIR "/neo_mesh.vert.spv");cfg.fragmentSpv=ReadSpv(NEO_SHADER_DIR "/neo_mesh.frag.spv");cfg.cullMode=VK_CULL_MODE_NONE;cfg.depthTestEnable=false;cfg.depthWriteEnable=false;cfg.vertexBinding={0,sizeof(NeoEngine::MeshVertex3D),VK_VERTEX_INPUT_RATE_VERTEX};cfg.vertexAttributes={{0,0,VK_FORMAT_R32G32B32_SFLOAT,0},{1,0,VK_FORMAT_R32G32B32_SFLOAT,12},{2,0,VK_FORMAT_R32G32_SFLOAT,24},{3,1,VK_FORMAT_R32G32B32A32_SFLOAT,0},{4,1,VK_FORMAT_R32G32B32A32_SFLOAT,16},{5,1,VK_FORMAT_R32G32B32A32_SFLOAT,32},{6,1,VK_FORMAT_R32G32B32A32_SFLOAT,48}};cfg.additionalVertexBindings={{1,sizeof(Instance),VK_VERTEX_INPUT_RATE_INSTANCE}};cfg.pushConstantRanges={{VK_SHADER_STAGE_VERTEX_BIT,0,sizeof(float)*16}};NeoEngine::VulkanGraphicsPipeline pipeline;if(!pipeline.Initialize(device,cfg))return 1;
GPUDrivenRenderer indirect;if(!indirect.Initialize(device,physical,2)||!indirect.TrySubmitDraw({3,1,0,0,0})||!indirect.TrySubmitDraw({3,1,3,3,1}))return 1;VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};if(vkBeginCommandBuffer(r.commandBuffer,&begin)!=VK_SUCCESS)return 1;VkClearValue clear{};clear.color={{0,0,0,1}};VkRenderPassBeginInfo rbi{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};rbi.renderPass=r.renderPass;rbi.framebuffer=r.framebuffer;rbi.renderArea.extent={kWidth,kHeight};rbi.clearValueCount=1;rbi.pClearValues=&clear;vkCmdBeginRenderPass(r.commandBuffer,&rbi,VK_SUBPASS_CONTENTS_INLINE);VkViewport vp{0,0,(float)kWidth,(float)kHeight,0,1};VkRect2D sc{{0,0},{kWidth,kHeight}};vkCmdSetViewport(r.commandBuffer,0,1,&vp);vkCmdSetScissor(r.commandBuffer,0,1,&sc);vkCmdBindPipeline(r.commandBuffer,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline.GetPipeline());VkBuffer vbs[2]={batch.GetVertexBuffer().GetBuffer(),ib.GetBuffer()};VkDeviceSize offs[2]={0,0};vkCmdBindVertexBuffers(r.commandBuffer,0,2,vbs,offs);vkCmdBindIndexBuffer(r.commandBuffer,batch.GetIndexBuffer().GetBuffer(),0,VK_INDEX_TYPE_UINT32);float identity[16]{};identity[0]=identity[5]=identity[10]=identity[15]=1;vkCmdPushConstants(r.commandBuffer,pipeline.GetPipelineLayout(),VK_SHADER_STAGE_VERTEX_BIT,0,sizeof(identity),identity);if(!indirect.Execute(r.commandBuffer)||indirect.PendingDrawCount()!=0)return 1;vkCmdEndRenderPass(r.commandBuffer);VkBufferImageCopy copy{};copy.bufferRowLength=kWidth;copy.bufferImageHeight=kHeight;copy.imageSubresource.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;copy.imageSubresource.layerCount=1;copy.imageExtent={kWidth,kHeight,1};vkCmdCopyImageToBuffer(r.commandBuffer,r.image,VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,r.readback,1,&copy);if(vkEndCommandBuffer(r.commandBuffer)!=VK_SUCCESS)return 1;
VkFenceCreateInfo fenceInfo{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};if(vkCreateFence(device,&fenceInfo,nullptr,&r.fence)!=VK_SUCCESS)return 1;VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.commandBufferCount=1;submit.pCommandBuffers=&r.commandBuffer;if(vkQueueSubmit(queue,1,&submit,r.fence)!=VK_SUCCESS||vkWaitForFences(device,1,&r.fence,VK_TRUE,std::numeric_limits<uint64_t>::max())!=VK_SUCCESS)return 1;void* mapped=nullptr;if(vkMapMemory(device,r.readbackMemory,0,bytes,0,&mapped)!=VK_SUCCESS)return 1;const uint8_t* pixels=static_cast<const uint8_t*>(mapped);uint32_t nonClear=0;for(VkDeviceSize i=0;i<bytes;i+=4)if(pixels[i]||pixels[i+1]||pixels[i+2])++nonClear;vkUnmapMemory(device,r.readbackMemory);if(nonClear==0)return 1;std::printf("R3_GPU_INDIRECT_OK draws=2 non_clear_pixels=%u\n",nonClear);
pipeline.Destroy();ib.Destroy();indirect.Destroy();batch.Destroy();a.Destroy();b.Destroy();vkDestroyDevice(device,nullptr);r.device=VK_NULL_HANDLE;vkDestroyInstance(instance,nullptr);return 0;}
