#include "GameTemplateRegistry.h"
#include <array>
namespace NeoEngine {
namespace { constexpr std::array<GameTemplateDefinition,30> kTemplates{{
{"sudoku","puzzle",TemplateReadiness::ExecutableRuntime,false},{"farm-sim","simulation",TemplateReadiness::CatalogOnly,true},{"tower-defense","strategy",TemplateReadiness::ExecutableRuntime,true},{"match-three","puzzle",TemplateReadiness::ExecutableRuntime,false},{"endless-runner","arcade",TemplateReadiness::CatalogOnly,false},{"idle-clicker","idle",TemplateReadiness::CatalogOnly,true},{"merge-game","casual",TemplateReadiness::CatalogOnly,true},{"word-puzzle","puzzle",TemplateReadiness::CatalogOnly,false},{"solitaire","card",TemplateReadiness::CatalogOnly,false},{"checkers","board",TemplateReadiness::CatalogOnly,false},{"chess-tactics","board",TemplateReadiness::CatalogOnly,false},{"bubble-shooter","arcade",TemplateReadiness::CatalogOnly,false},{"brick-breaker","arcade",TemplateReadiness::CatalogOnly,false},{"pinball","arcade",TemplateReadiness::CatalogOnly,false},{"tap-rpg","rpg",TemplateReadiness::CatalogOnly,true},{"turn-rpg","rpg",TemplateReadiness::CatalogOnly,true},{"dungeon-crawler","rpg",TemplateReadiness::ExecutableRuntime,true},{"card-battler","card",TemplateReadiness::CatalogOnly,true},{"auto-battler","strategy",TemplateReadiness::CatalogOnly,true},{"city-builder","simulation",TemplateReadiness::CatalogOnly,true},{"restaurant-sim","simulation",TemplateReadiness::CatalogOnly,true},{"fishing-sim","simulation",TemplateReadiness::CatalogOnly,true},{"pet-collector","collection",TemplateReadiness::CatalogOnly,true},{"dress-up","casual",TemplateReadiness::CatalogOnly,true},{"platformer","action",TemplateReadiness::CatalogOnly,false},{"top-down-shooter","action",TemplateReadiness::CatalogOnly,false},{"racing","racing",TemplateReadiness::CatalogOnly,false},{"rhythm","music",TemplateReadiness::CatalogOnly,false},{"hidden-object","puzzle",TemplateReadiness::CatalogOnly,false},{"escape-room","puzzle",TemplateReadiness::CatalogOnly,false}
}}; }
std::span<const GameTemplateDefinition> GameTemplateRegistry::All(){ return kTemplates; }
const GameTemplateDefinition* GameTemplateRegistry::Find(std::string_view key){ for(const auto& value:kTemplates) if(value.key==key) return &value; return nullptr; }
bool GameTemplateRegistry::CanIssueExecutablePlan(std::string_view key){ const auto* value=Find(key); return value && value->readiness==TemplateReadiness::ExecutableRuntime; }
} // namespace NeoEngine
