#include "OpenCodeIntegration.h"
#include <curl/curl.h>
#include <json/json.h>
#include <android/log.h>

#define LOG_TAG_OC "OpenCodeIntegration"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG_OC, __VA_ARGS__)

namespace NeoEngine {

static size_t WriteCallback(void* contents, size_t size, size_t nmemb, std::string* output) {
    size_t totalSize = size * nmemb;
    output->append(static_cast<char*>(contents), totalSize);
    return totalSize;
}

OpenCodeIntegration::OpenCodeIntegration() : ready(false) {}

OpenCodeIntegration::~OpenCodeIntegration() { Shutdown(); }

bool OpenCodeIntegration::Initialize() {
    CURL* curl = curl_easy_init();
    if (!curl) { ready = false; return false; }
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:5000/health");
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 2L);
    CURLcode res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
    ready = (res == CURLE_OK);
    LOGI("OpenCode integration %s", ready ? "connected" : "using local generation");
    return true;
}

void OpenCodeIntegration::Shutdown() { ready = false; }

GeneratedCode OpenCodeIntegration::GenerateFromDescription(const std::string& desc) {
    GeneratedCode gc;
    if (!ready) {
        // Fallback: generate template code locally
        gc.language = "cpp";
        gc.code = "// Generated by NeoEngine OpenCode for: " + desc + "\n"
                  "void GeneratedFeature() {\n"
                  "    // TODO: AI-powered implementation\n"
                  "}\n";
        gc.description = desc;
        gc.complexity = 3;
        return gc;
    }

    CURL* curl = curl_easy_init();
    if (!curl) return gc;

    Json::Value body;
    body["prompt"] = "Generate C++ game engine code for: " + desc;
    body["max_tokens"] = 2048;

    Json::FastWriter writer;
    std::string jsonBody = writer.write(body);

    std::string responseStr;
    struct curl_slist* headers = nullptr;
    headers = curl_slist_append(headers, "Content-Type: application/json");
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:8765/v1/chat/completions");
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, jsonBody.c_str());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &responseStr);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 60L);

    CURLcode res = curl_easy_perform(curl);
    curl_slist_free_all(headers);
    curl_easy_cleanup(curl);

    gc.language = "cpp";
    gc.code = res == CURLE_OK ? responseStr : "// Failed to generate code\n";
    gc.description = desc;
    gc.complexity = 5;
    return gc;
}

GeneratedCode OpenCodeIntegration::GenerateFromTemplate(const std::string& tmpl,
    const std::map<std::string, std::string>& params) {
    GeneratedCode gc;
    gc.language = "cpp";
    gc.code = "// Template: " + tmpl + "\n";
    for (const auto& [k, v] : params) {
        gc.code += "// " + k + " = " + v + "\n";
    }
    gc.description = "From template " + tmpl;
    gc.complexity = 2;
    return gc;
}

std::vector<std::string> OpenCodeIntegration::GetSupportedLanguages() const {
    return {"cpp", "python", "javascript", "typescript", "java", "csharp"};
}

bool OpenCodeIntegration::ValidateCode(const GeneratedCode& code) {
    return !code.code.empty() && code.code.length() > 10;
}

bool OpenCodeIntegration::IsReady() const { return ready; }

} // namespace NeoEngine
