#include "Runtime/SceneMeshAdapter.h"
#include "Runtime/MaterialStaging.h"
#include "Runtime/MeshStaging.h"
#include "Runtime/SoftwareRenderer.h"

#include <cstdio>
#include <string>

int main() {
    using namespace NeoEngine;
    const std::vector<MeshVertex> triangle{{{-1,-1,0},{0,0,-1},0,0},{{1,-1,0},{0,0,-1},1,0},{{0,1,0},{0,0,-1},0.5F,1}};
    const std::vector<uint16_t> indices{0,1,2};
    const MeshMaterial material{0xFFFF0000U,0.2F,0.8F,nullptr};
    SceneWorld world;
    SceneEntity parent{},child{},culled{};
    if(!world.Create(parent)||!world.Create(child)||!world.Create(culled)||!world.SetTransform(parent,{0,0,5,0,0,0.25F,1,1,1})||!world.SetTransform(child,{0,0,1,0,0,0.35F,1,1,1})||!world.SetTransform(culled,{100,0,6,0,0,0,1,1,1})||!world.SetParent(child,parent)||!world.UpdateTransforms()) return 1;
    RenderCamera camera;
    if(!camera.Initialize({RenderCameraMode::Perspective,{0,0,0},5,90,1,0.1F,20})) return 1;
    SoftwareRenderer renderer;
    if(!renderer.Initialize(64,64)||!renderer.Clear(0xFF000000U)) return 1;
    SceneMeshAdapter adapter;
    if(!adapter.Add({child,triangle,indices,material})||!adapter.Add({culled,triangle,indices,material})||!adapter.Draw(world,camera,renderer,{{0,0,-1}})||adapter.LastCulledCount()!=1U||renderer.PixelAt(32,32)==0xFF000000U||renderer.FrameHash()==0U) return 1;
    const uint64_t hash=renderer.FrameHash();
    SoftwareRenderer repeated;
    if(!repeated.Initialize(64,64)||!repeated.Clear(0xFF000000U)||!adapter.Draw(world,camera,repeated,{{0,0,-1}})||adapter.LastCulledCount()!=1U||repeated.FrameHash()!=hash) return 1;
    if(!world.SetTransform(parent,{0,0,5,0,0,0,1,1,1})||!world.SetTransform(child,{0,0,1,0,0,0,1,1,1})||!world.UpdateTransforms()) return 1;
    SoftwareRenderer unrotated;
    if(!unrotated.Initialize(64,64)||!unrotated.Clear(0xFF000000U)||!adapter.Draw(world,camera,unrotated,{{0,0,-1}})||adapter.LastCulledCount()!=1U||unrotated.FrameHash()==hash) return 1;
    SceneMeshAdapter missing;
    if(!missing.Add({{99,1},triangle,indices,material})||missing.Draw(world,camera,renderer,{{0,0,-1}})||missing.LastError()!=SceneMeshAdapterError::MissingEntity) return 1;
    SceneMeshAdapter unsupported;
    if(!world.SetTransform(culled,{100,0,6,0,0,0,1,2,1})||!unsupported.Add({culled,triangle,indices,material})||unsupported.Draw(world,camera,renderer,{{0,0,-1}})||unsupported.LastError()!=SceneMeshAdapterError::UnsupportedTransform) return 1;
    const auto bytes=[](const std::string& value){return std::vector<uint8_t>(value.begin(),value.end());};const std::string stagedObj="v -1 -1 0\nv 1 -1 0\nv 0 1 0\nvn 0 0 -1\nf 1//1 2//1 3//1\n";
    const std::string stagedMtl="newmtl grass\nKd 0.1 0.8 0.2\nd 1\n";const std::vector<uint8_t> stagedPpm{'P','6','\n','1',' ','1','\n','2','5','5','\n',255U,0U,0U};AssetRegistry registry;if(!registry.ImportBytes("scene.mesh",AssetKind::Mesh,{},bytes(stagedObj))||!registry.MarkReady("scene.mesh")||!registry.ImportBytes("scene.material",AssetKind::Material,{},bytes(stagedMtl))||!registry.MarkReady("scene.material")||!registry.ImportBytes("scene.texture",AssetKind::Texture,{},stagedPpm)||!registry.MarkReady("scene.texture"))return 1;MeshStagingStore staging;if(!staging.StageObj(registry,"scene.mesh"))return 1;MaterialStagingStore materialStaging;if(!materialStaging.StageMtl(registry,"scene.material","grass"))return 1;TextureStagingStore textureStaging;if(!textureStaging.StagePpm(registry,"scene.texture"))return 1;
    SceneWorld stagedWorld;SceneEntity stagedEntity{},textureEntity{};if(!stagedWorld.Create(stagedEntity)||!stagedWorld.Create(textureEntity)||!stagedWorld.SetTransform(stagedEntity,{0,0,5,0,0,0,1,1,1})||!stagedWorld.SetTransform(textureEntity,{0,0,5,0,0,0,1,1,1})||!stagedWorld.UpdateTransforms())return 1;
    SceneMeshAdapter stagedAdapter;const CpuMeshResource* stagedResource=staging.Find("scene.mesh");if(stagedResource==nullptr||!stagedAdapter.AddStaged(stagedEntity,*stagedResource,{0xFF00FF00U,0.2F,0.8F,nullptr}))return 1;SoftwareRenderer stagedRenderer;if(!stagedRenderer.Initialize(64,64)||!stagedRenderer.Clear(0xFF000000U)||!stagedAdapter.Draw(stagedWorld,camera,stagedRenderer,{{0,0,-1}})||stagedRenderer.PixelAt(32,32)==0xFF000000U||stagedRenderer.FrameHash()==0U)return 1;
    CpuMeshResource invalid{};invalid.sourceHash=1U;SceneMeshAdapter invalidAdapter;if(invalidAdapter.AddStaged(stagedEntity,invalid,material)||invalidAdapter.LastError()!=SceneMeshAdapterError::InvalidStagedResource)return 1;
    const CpuMaterialResource* stagedMaterial=materialStaging.Find("scene.material","grass");SceneMeshAdapter pairedAdapter;if(stagedMaterial==nullptr||!pairedAdapter.AddStaged(stagedEntity,*stagedResource,*stagedMaterial))return 1;SoftwareRenderer pairedRenderer;if(!pairedRenderer.Initialize(64,64)||!pairedRenderer.Clear(0xFF000000U)||!pairedAdapter.Draw(stagedWorld,camera,pairedRenderer,{{0,0,-1}}))return 1;const uint32_t pairedPixel=pairedRenderer.PixelAt(32,32);if(pairedPixel==0xFF000000U||((pairedPixel>>8U)&0xFFU)<=((pairedPixel>>16U)&0xFFU))return 1;CpuMaterialResource invalidMaterial{};invalidMaterial.sourceHash=1U;SceneMeshAdapter invalidMaterialAdapter;if(invalidMaterialAdapter.AddStaged(stagedEntity,*stagedResource,invalidMaterial)||invalidMaterialAdapter.LastError()!=SceneMeshAdapterError::InvalidStagedMaterial)return 1;
    const std::string refreshedObj="v -0.9 -0.9 0\nv 0.9 -0.9 0\nv 0 0.9 0\nvn 0 0 -1\nf 1//1 2//1 3//1\n";const std::string refreshedMtl="newmtl grass\nKd 0.8 0.1 0.2\nd 1\n";if(!registry.ReplaceBytes("scene.mesh",bytes(refreshedObj))||!registry.ReplaceBytes("scene.material",bytes(refreshedMtl))||!staging.Refresh(registry,"scene.mesh")||!materialStaging.Refresh(registry,"scene.material","grass")||staging.IsCurrent(registry,"scene.mesh")==false||materialStaging.IsCurrent(registry,"scene.material","grass")==false)return 1;
    SoftwareRenderer copiedRenderer;if(!copiedRenderer.Initialize(64,64)||!copiedRenderer.Clear(0xFF000000U)||!pairedAdapter.Draw(stagedWorld,camera,copiedRenderer,{{0,0,-1}})||copiedRenderer.PixelAt(32,32)!=pairedPixel)return 1;
    if(!stagedAdapter.RefreshStaged(stagedEntity,*stagedResource,{0xFF00FF00U,0.2F,0.8F,nullptr})||!pairedAdapter.RefreshStaged(stagedEntity,*stagedResource,*stagedMaterial))return 1;SoftwareRenderer refreshedRenderer;if(!refreshedRenderer.Initialize(64,64)||!refreshedRenderer.Clear(0xFF000000U)||!pairedAdapter.Draw(stagedWorld,camera,refreshedRenderer,{{0,0,-1}}))return 1;const uint32_t refreshedPixel=refreshedRenderer.PixelAt(32,32);if(refreshedPixel==pairedPixel||((refreshedPixel>>16U)&0xFFU)<=((refreshedPixel>>8U)&0xFFU))return 1;
    CpuMeshResource mismatchedMesh=*stagedResource;mismatchedMesh.assetId="other.mesh";if(pairedAdapter.RefreshStaged(stagedEntity,mismatchedMesh,*stagedMaterial)||pairedAdapter.LastError()!=SceneMeshAdapterError::InvalidStagedResource)return 1;CpuMaterialResource mismatchedMaterial=*stagedMaterial;mismatchedMaterial.materialName="other";if(pairedAdapter.RefreshStaged(stagedEntity,*stagedResource,mismatchedMaterial)||pairedAdapter.LastError()!=SceneMeshAdapterError::InvalidStagedMaterial)return 1;SoftwareRenderer afterRejectedRebind;if(!afterRejectedRebind.Initialize(64,64)||!afterRejectedRebind.Clear(0xFF000000U)||!pairedAdapter.Draw(stagedWorld,camera,afterRejectedRebind,{{0,0,-1}})||afterRejectedRebind.PixelAt(32,32)!=refreshedPixel)return 1;
    const CpuTextureResource* stagedTexture=textureStaging.Find("scene.texture");MeshMaterial textureMaterial{0xFFFFFFFFU,0.2F,0.8F,stagedTexture};SceneMeshAdapter textureAdapter;if(stagedTexture==nullptr||!textureAdapter.AddStaged(textureEntity,*stagedResource,textureMaterial)||!textureAdapter.CanRefreshStaged(textureEntity,*stagedResource,textureMaterial))return 1;SoftwareRenderer textureRenderer;if(!textureRenderer.Initialize(64,64)||!textureRenderer.Clear(0xFF000000U)||!textureAdapter.Draw(stagedWorld,camera,textureRenderer,{{0,0,-1}})||textureRenderer.PixelAt(32,32)!=0xFFFF0000U)return 1;const std::vector<uint8_t> bluePpm{'P','6','\n','1',' ','1','\n','2','5','5','\n',0U,0U,255U};if(!registry.ReplaceBytes("scene.texture",bluePpm)||!textureStaging.Refresh(registry,"scene.texture"))return 1;SoftwareRenderer copiedTextureRenderer;if(!copiedTextureRenderer.Initialize(64,64)||!copiedTextureRenderer.Clear(0xFF000000U)||!textureAdapter.Draw(stagedWorld,camera,copiedTextureRenderer,{{0,0,-1}})||copiedTextureRenderer.PixelAt(32,32)!=0xFFFF0000U||!textureAdapter.CanRefreshStaged(textureEntity,*stagedResource,textureMaterial)||!textureAdapter.RefreshStaged(textureEntity,*stagedResource,textureMaterial))return 1;SoftwareRenderer reboundTextureRenderer;if(!reboundTextureRenderer.Initialize(64,64)||!reboundTextureRenderer.Clear(0xFF000000U)||!textureAdapter.Draw(stagedWorld,camera,reboundTextureRenderer,{{0,0,-1}})||reboundTextureRenderer.PixelAt(32,32)!=0xFF0000FFU)return 1;CpuTextureResource wrongTexture=*stagedTexture;wrongTexture.assetId="other.texture";MeshMaterial wrongTextureMaterial{0xFFFFFFFFU,0.2F,0.8F,&wrongTexture};if(textureAdapter.CanRefreshStaged(textureEntity,*stagedResource,wrongTextureMaterial)||textureAdapter.RefreshStaged(textureEntity,*stagedResource,wrongTextureMaterial)||textureAdapter.LastError()!=SceneMeshAdapterError::InvalidStagedTexture)return 1;SoftwareRenderer afterRejectedTexture;if(!afterRejectedTexture.Initialize(64,64)||!afterRejectedTexture.Clear(0xFF000000U)||!textureAdapter.Draw(stagedWorld,camera,afterRejectedTexture,{{0,0,-1}})||afterRejectedTexture.PixelAt(32,32)!=0xFF0000FFU)return 1;
    std::printf("SCENE_MESH_ADAPTER_SMOKE_OK worldTransform=1 rotation=1 culled=1 staged=1 paired=1 textureCopy=1 rebind=1 rebindProbe=1 pixel=1 hash=%llu\n",static_cast<unsigned long long>(hash));return 0;
}
